exec FMK.spAddLookup 'AccountType',0,'   ','   ','',N'','ACC',0,'' 
exec FMK.spAddLookup 'AccountType',1,'گروه','CL',N'گرووپ',N'مجموعة','ACC',1,''
exec FMK.spAddLookup 'AccountType',2,'كل','GL',N'سەرجەم',N'المجموع','ACC',2,''
exec FMK.spAddLookup 'AccountType',3,'معين','SL',N'ياريدەر',N'المحدّد','ACC',3,''

exec FMK.spAddLookup 'BalanceType',1,'بدهكار','Debit Balance',N'قەرزدار',N'المدين','ACC',1,''
exec FMK.spAddLookup 'BalanceType',2,'بستانكار','Credit Balance',N'خاوەن قەرز',N'الدائن','ACC',2,''
exec FMK.spAddLookup 'BalanceType',3,'مهم نيست','Don''t Care',N'گرنگ نييە',N'ليس الهام','ACC',3,''

exec FMK.spAddLookup 'CashFlowCategory',0,'ندارد','None',N'نييەتي',N'لا','ACC',0,''
exec FMK.spAddLookup 'CashFlowCategory',1,'عملياتي','Operational',N'كردەيي',N'العملية','ACC',1,''
exec FMK.spAddLookup 'CashFlowCategory',2,'سرمايه گذاري','Investment',N'سەرمايە دانان',N'استثمار','ACC',2,''
exec FMK.spAddLookup 'CashFlowCategory',3,'تامين مالي','Financing',N'دابينكاريي ماڵيي',N'التمويل و تزويد مالي','ACC',3,''

exec FMK.spAddLookup 'DLType',0,'','','','','ACC',1,''
exec FMK.spAddLookup 'DLType',1,'ساير','Other',N'ديكە',N'الآخر','ACC',1,''
exec FMK.spAddLookup 'DLType',2,'طرف مقابل','Party',N'لايه‌ن مامه‌ڵه‌',N'الطرف الآخر','ACC',2,''
exec FMK.spAddLookup 'DLType',3,'مركز هزينه','Cost Center',N'ناوەندي خەرج',N'مركز التكلفة','ACC',3,''
exec FMK.spAddLookup 'DLType',4,'حساب بانكي','Bank Account',N'ژمێرەي بانكي',N'الحساب المصرفي','ACC',4,''
exec FMK.spAddLookup 'DLType',5,'صندوق','Cash',N'بوخچە',N'صندوق','ACC',5,''
exec FMK.spAddLookup 'DLType',6,'دستگاه كارت خوان','POS',N'ئامێري كارت‌ناس',N'جهاز قارئ بطاقة','ACC',6,''
exec FMK.spAddLookup 'DLType',7,'قرارداد','Contract',N'گرێبەست',N'العقد','ACC',7,''
exec FMK.spAddLookup 'DLType',8,'سفارش خريد','Purchase Order',N'',N'','ACC',8,''


exec FMK.spAddLookup 'TopicCategory',1,'داراييهاي غير جاري','Non-current assets',N'سامانه‌ نه‌گه‌ڕه‌كان',N'ممتلكات غير المتداولة','ACC',1,''
exec FMK.spAddLookup 'TopicCategory',2,'داراييهاي جاري','Current assets',N'سامانه‌ له‌گه‌ڕه‌كان','الممتلكات المتداولة','ACC',2,''
exec FMK.spAddLookup 'TopicCategory',3,'حقوق صاحبان سهام','Equity',N'خاوەن سەرمايە',N'أجور و أرباح المساهمين','ACC',3,''
exec FMK.spAddLookup 'TopicCategory',4,'بدهي هاي غير جاري','Non-current debts',N'قه‌رزه‌ نه‌گه‌ڕه‌كان',N'ديون غير المتداولة','ACC',4,''
exec FMK.spAddLookup 'TopicCategory',5,'بدهي هاي جاري','Current debts',N'قه‌رزه‌ له‌ گه‌ڕه‌كان','ديون المتداولة','ACC',5,''
exec FMK.spAddLookup 'TopicCategory',6,'سود و زياني - فروش خالص','Profit (loss) - net sales',N'سوود و زيان -  پۆختەي فرۆش',N'الربح والخسارة - صافي المبيعات','ACC',6,''
exec FMK.spAddLookup 'TopicCategory',7,'سود و زياني - بهاي تمام شده','Profit (loss) - Cost',N'سوود و زيان -  نرخي كۆتايي',N'الربح والخسارة - سعر التكلفة','ACC',7,''
exec FMK.spAddLookup 'TopicCategory',8,'سود و زياني - سود حاصل از سرمايه گذاري هاي عملياتي','Profit (loss) - Profit arising from operational investments',N'سوود و زيان -  سوودي سەرمايەگوزارييە كردەوەييەكان',N'الربح والخسارة -  الربح الناتج من الاستثمارات التشغيلية','ACC',8,''
exec FMK.spAddLookup 'TopicCategory',9,'سود و زياني - ساير درامد ها و هزينه هاي عملياتي ، فروش ، اداري عمومي','Profit (loss) - Other operating, sales, and administrative incomes and costs',N'سوود و زيان -  داهات و خەرجەكاني تري كردەوەيي، فرۆش، كارگێريي گشتي',N'الربح والخسارة -  الإيرادات والمصروفات التشغيلية الأخرى والمبيعات والإدارة العامة','ACC',9,''
exec FMK.spAddLookup 'TopicCategory',10,'سود و زياني - ساير درامد ها و هزينه هاي غير عملياتي و مالي','Profit (loss) - Other non-operational and financial incomes and costs',N'سوود و زيان -  داهات و خەرجە ناكردەوەييەكاني تر',N'الربح والخسارة -  الإيرادات والمصروفات غير التشغيلية والمالية الأخرى','ACC',10,''
exec FMK.spAddLookup 'TopicCategory',11,'سود و زياني - مالياتي','Profit (loss) - Tax',N'سوود و زيان -  باج',N'الربح والخسارة - الضريبية','ACC',11,''
exec FMK.spAddLookup 'TopicCategory',12,'سود و زياني - عمليات متوقف شده','Profit (loss) - Discontinued operations',N'سوود و زيان -  كاره‌ ڕاگيراوەكان',N'الربح والخسارة - العمليات المتوقفة','ACC',12,''

exec FMK.spAddLookup 'TopicType',1,'ترازنامه اي','Balance Sheet',N'ترازنامە',N'الميزانية العمومية','ACC',1,''
exec FMK.spAddLookup 'TopicType',2,'سود و زياني','Profit Or Loss',N'قازانج و زيان',N'الربح والخسارة','ACC',2,''