exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsGLVoucher.FrmGLVoucher', N'تجميع، صدور سند روزانه، تجميعي، ادغام، دفتر نويسي، نوشتن دفاتر قانوني، تحرير', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsGLVoucher.List', N'فهرست اسناد كل، صادر شده، تجميع، روزانه', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsOpeningOperation.OpeningOperationFrom', N'استقرار، سند افتتاحيه سال اول', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsVoucher.FrmChangeVoucherState', N'دائم كردن، قطعي كردن، موقت كردن ، قفل كردن', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsVoucher.FrmCloseAccounts_AllAccounts', N'جابجايي، انتقال مانده، تغيير حساب معين', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsVoucher.FrmCloseAccounts_IncomeExpenseAccounts', N'موقت، محاسبه سود و زيان دوره، صفر كردن هزينه ها، درآمدها، عملكرد', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsVoucher.FrmClosingOpening', N'بستن حسابهاي دائم، عمليات پايان سال حسابداري، ترازنامه اي، انتقال مانده', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsVoucher.FrmCurrencyConversion', N'نوسانات، تغييرات نرخ', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsVoucher.List', N'فهرست اسناد، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsVoucher.New', N'ثبت، روكش سند، voucher، شابلون، اسناد مالي', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DsVoucher.ReorderVoucherNumbers', N'مرتب سازي، Sort، تغيير شماره سند', N'', N'', N''
exec FMK.spAddKeyword 'Accounting.VoucherManagement.DummyEntity.ShowReview', N'گزارش، گزارشات مالي، گردش معين، حسابها، تفصيل، بد و بس، مانده در خط', N'', N'', N''
