exec FMK.spAddLookup 'ReportRowCountLimits',10,'10','10',N'10',N'10','GNR',10,''
exec FMK.spAddLookup 'ReportRowCountLimits',25,'25','25',N'25',N'25','GNR',25,''
exec FMK.spAddLookup 'ReportRowCountLimits',50,'50','50',N'50',N'50','GNR',50,''
exec FMK.spAddLookup 'ReportRowCountLimits',100,'100','100',N'100',N'100','GNR',100,''
exec FMK.spAddLookup 'ReportRowCountLimits',2147483646,'همه موارد','All',N'',N'','GNR',2147483646,''

exec FMK.spAddLookup 'ManagementReportCompareOptions',0,'مقايسه - خالي','Compare - None',N'',N'','GNR',0,''
exec FMK.spAddLookup 'ManagementReportCompareOptions',1,'مقايسه - با 1 سال گذشته','Compare - To Last Year',N'',N'','GNR',1,''
exec FMK.spAddLookup 'ManagementReportCompareOptions',2,'مقايسه - با 2 سال گذشته','Compare - To Last Two Years',N'',N'','GNR',2,''
exec FMK.spAddLookup 'ManagementReportCompareOptions',3,'مقايسه - با 3 سال گذشته','Compare - To Last Three Years',N'',N'','GNR',3,''

exec FMK.spAddLookup 'ManagementReportsPeriodType',1,'دوره زماني - روز','Period Type - Day',N'',N'','GNR',1,''
exec FMK.spAddLookup 'ManagementReportsPeriodType',2,'دوره زماني - هفته','Period Type - Week',N'',N'','GNR',2,''
exec FMK.spAddLookup 'ManagementReportsPeriodType',3,'دوره زماني - ماه','Period Type - Month',N'',N'','GNR',3,''
exec FMK.spAddLookup 'ManagementReportsPeriodType',4,'دوره زماني - فصل','Period Type - Season',N'',N'','GNR',4,''
exec FMK.spAddLookup 'ManagementReportsPeriodType',5,'دوره زماني - سال','Period Type - Year',N'',N'','GNR',5,''

exec FMK.spAddLookup 'ReportLogicalOperator',0,'','',N'',N'','GNR',0,''
exec FMK.spAddLookup 'ReportLogicalOperator',1,'و','And',N'و',N'و','GNR',1,''
exec FMK.spAddLookup 'ReportLogicalOperator',2,'يا','Or',N'يا',N'يا','GNR',2,''

exec FMK.spAddLookup 'ReportFilterOperator',0,'','',N'',N'','GNR',0,''
exec FMK.spAddLookup 'ReportFilterOperator',1,'برابر با','Equal To',N'',N'','GNR',1,''
exec FMK.spAddLookup 'ReportFilterOperator',2,'برابر نيست با','Not Equal To',N'',N'','GNR',2,''
exec FMK.spAddLookup 'ReportFilterOperator',3,'بزرگتر','Greater Than',N'',N'','GNR',3,''
exec FMK.spAddLookup 'ReportFilterOperator',4,'بزرگتر يا مساوي با','Greater Than Or Equal To',N'',N'','GNR',4,''
exec FMK.spAddLookup 'ReportFilterOperator',5,'كوچك تر','Less Than',N'',N'','GNR',5,''
exec FMK.spAddLookup 'ReportFilterOperator',6,'كوچكتر يا مساوي با','Less Than Or Equal To',N'',N'','GNR',6,''
exec FMK.spAddLookup 'ReportFilterOperator',7,'شامل','Contains',N'',N'','GNR',7,''
exec FMK.spAddLookup 'ReportFilterOperator',8,'شامل','Includes',N'',N'','GNR',8,''
exec FMK.spAddLookup 'ReportFilterOperator',9,'خالي است','Is Empty',N'',N'','GNR',13,''
exec FMK.spAddLookup 'ReportFilterOperator',10,'خالي نيست','Is Not Empty',N'',N'','GNR',14,''
exec FMK.spAddLookup 'ReportFilterOperator',11,'شروع مي شود با','Starts With',N'',N'','GNR',11,''
exec FMK.spAddLookup 'ReportFilterOperator',12,'پايان مي پذيرد با','Ends With',N'',N'','GNR',12,''
exec FMK.spAddLookup 'ReportFilterOperator',13,'شامل نمي شود از','Does Not Contain',N'',N'','GNR',9,''
exec FMK.spAddLookup 'ReportFilterOperator',14,'شامل نمي شود از','Does Not Include',N'',N'','GNR',10,''

exec FMK.spAddLookup 'CompanyDashboardRange',1,'سالانه','Yearly',N'',N'','GNR',1,''
exec FMK.spAddLookup 'CompanyDashboardRange',2,'فصلي','Quarter',N'',N'','GNR',2,''
exec FMK.spAddLookup 'CompanyDashboardRange',3,'ماهانه','Monthly',N'',N'','GNR',3,''
exec FMK.spAddLookup 'CompanyDashboardRange',4,'هفتگي','Weekly',N'',N'','GNR',4,''
exec FMK.spAddLookup 'CompanyDashboardRange',5,'روزانه','Daily',N'',N'','GNR',5,''

exec Fmk.spAddLookup 'SalaryChangeType',1,'افزايش','Increase',N'',N'','RPA',1,''
exec Fmk.spAddLookup 'SalaryChangeType',2,'كاهش','Decrease',N'',N'','RPA',2,''
exec Fmk.spAddLookup 'SalaryChangeType',3,'بدون تغيير','Not Changed',N'',N'','RPA',3,''

exec Fmk.spAddLookup 'BankFlowCompanyDashboardReportType',1,'1: موجودي بانك','1: Bank Balanace',N'1: هەبووي بانك',N'1: الممتلكات و لأموال النقدية للمصرف','RPA',1,''
exec Fmk.spAddLookup 'BankFlowCompanyDashboardReportType',2,'2: موجودي صندوق','2: Cash Balance',N'هەبووي بوخچە:2',N'2: أموال','RPA',2,''
exec Fmk.spAddLookup 'BankFlowCompanyDashboardReportType',3,'3: موجودي دستگاه كارت خوان','3: Pos Balance',N'هەبووي ئامێري كارت‌ناس:3',N'3: قارئ بطاقة المخزون','RPA',3,''
exec Fmk.spAddLookup 'BankFlowCompanyDashboardReportType',4,'4: موجودي تنخواه دار','4: Petty cash Balance',N'4: Petty cash Balance',N'4: Petty cash Balance','RPA',4,''
exec Fmk.spAddLookup 'BankFlowCompanyDashboardReportType',5,'5: تعهدات دريافتني','5: Recievable',N'بەڵێنەكان بۆ وەرگرتن:5',N'5: التعهدات المستحقة','RPA',5,''
exec Fmk.spAddLookup 'BankFlowCompanyDashboardReportType',6,'6: تعهدات پرداختني','6: Payable',N'بەڵێنەكان بۆ پێدان:6',N'6: الالتزامات المستحقة','RPA',6,''

exec FMK.spAddLookup 'Quarter',0,N'',N'',N'',N'','GNR',0,''
exec FMK.spAddLookup 'Quarter',1,N'اول',N'Q1',N'',N'','GNR',1,''
exec FMK.spAddLookup 'Quarter',2,N'دوم',N'Q2',N'',N'','GNR',2,''
exec FMK.spAddLookup 'Quarter',3,N'سوم',N'Q3',N'',N'','GNR',3,''
exec FMK.spAddLookup 'Quarter',4,N'چهارم',N'Q4',N'',N'','GNR',4,''