exec FMK.spAddKeyword 'Contract.ContractOperation.DsCoefficient.List', N'فهرست ضرايب قرارداد، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsCoefficient.New', N'قرارداد، حسن انجام كار، ارزش افزوده، ضرايب افزاينده، ضرايب كاهنده', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsContract.List', N'فهرست قرارداد، پيمانها، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsContract.New', N'دست دو، پيمانكارجزء، پيش دريافت، علي الحساب، مصالح دريافتي، توافقات، تعديل، الحاقيه، دستوركار، صورتجلسه، متمم، هزينه', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsCost.List', N'فهرست انواع هزينه پيمانها، پروژه ها، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsCost.New', N'پروژه، پيمان، پيمانكار جزء، حقوق پرسنل، سربار، استهلاك انباشته، مواد و مصالح مصرفي', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsCostStatement.List', N'فهرست هزينه هاي قرارداد، پيمان، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsCostStatement.New', N'هزينه، پيمان، قرارداد، صورت هزينه، نقدي، اعتباري، كارگاهي، دفتر مركزي، تنخواه گردان كارگاه', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsGuarantee.List', N'فهرست ضمانت نامه هاي دريافتي، پرداختي، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsGuarantee.New', N'مناقصه، حسن انجام كار، تعهدات قرارداد، پيمانكار دست دو، پيمانكار جزء، چك تضميني، سفته', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsProject.List', N'فهرست پروژه، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsSettlement.List', N'فهرست تسويه جساب، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsSettlement.New', N'تسويه صورت وضعيت، تسويه صورت هزينه اعتباري', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsStatus.List', N'فهرست صورت وضعيت، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsStatus.New', N'تاييد صورت وضعيت، قطعي، ماقبل قطعي، تعديل افزايشي، تعديل كاهشي', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsTender.List', N'فهرست مناقصه هاي ثبت شده، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsTender.New', N'شركت در مناقصه، هزينه، ضمانتنامه شركت', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DsWorkshop.List', N'فهرست كارگاه، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DummyEntity.ShowFrmContractPriceList', N'دريافت از اكسل', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DummyEntity.ShowReview', N'گزارش، ريزهزينه، درآمد، مناقصه برنده شده، ضمانتنامه آزادنشده، صورت وضعيت ارسال، تاييد، مانده حساب', N'', N'', N''
exec FMK.spAddKeyword 'Contract.ContractOperation.DummyEntity.ShowReview_OwnerShip', N'گزارش، مانده حساب، صورت وضعيت، صورت وضعيت هاي تاييد شده، ضمانتنامه هاي دريافتي', N'', N'', N''
