exec FMK.spAddKeyword 'Distribution.BasicData.DsProductSaleLine.List', N'فهرست خط فروش كالا، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.BasicData.DsProductSaleLine.New', N'لاين فروش، لاين بندي', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.BasicData.DsSalesLimit.List', N'فهرست سقف سفارش كالا، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.BasicData.DsSalesLimit.New', N'سقف فروش، محدوديت فروش كالا، محدوديت فروش ويزيتور', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.BasicData.DsSaleTypeConstraint.List', N'فهرست محدوديت خط فروش، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.BasicData.DsSaleTypeConstraint.New', N'ويزيتور، قيمت فروش ويزيتور', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.BasicData.DsUnexecutedActReason.List', N'فهرست علت هاي عدم انجام فعاليت، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.BasicData.DsUnexecutedActReason.New', N'دليل عدم انجام فعاليت', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.BasicData.DummyEntity.AreaAndPathTree', N'مناطق، مسيربندي', N'', N'', N''
