EXEC FMK.spAddLookup 'ColdDistributionState', 0, N'',				'',						N'', N'', 'DST', 0, ''
EXEC FMK.spAddLookup 'ColdDistributionState', 1, N'ثبت شده',		'Registered',			N'', N'', 'DST', 1, ''
EXEC FMK.spAddLookup 'ColdDistributionState', 2, N'خاتمه يافته',	'Dismissed',			N'', N'', 'DST', 2, ''
EXEC FMK.spAddLookup 'ColdDistributionState', 3, N'آماده توزيع',	'Ready To Distribute',	N'', N'', 'DST', 3, ''
EXEC FMK.spAddLookup 'ColdDistributionState', 4, N'در حال توزيع',	'Distributing',			N'', N'', 'DST', 4, ''
EXEC FMK.spAddLookup 'ColdDistributionState', 5, N'توزيع شده', 	    'Distributed',	        N'', N'', 'DST', 5, ''

EXEC FMK.spAddLookup 'ColdDistributionTrigger', 0, N'ثبت توزيع', 'Register Distribution', N'', N'', 'DST', 0, ''
EXEC FMK.spAddLookup 'ColdDistributionTrigger', 1, N'آماده توزيع', 'Ready To Distribute', N'', N'', 'DST', 1, ''
EXEC FMK.spAddLookup 'ColdDistributionTrigger', 2, N'برگشت از آماده توزيع', 'Return From Ready To Distribute', N'', N'', 'DST', 2, ''
EXEC FMK.spAddLookup 'ColdDistributionTrigger', 3, N'ارسال به دستگاه', 'Send To Device', N'', N'', 'DST', 3, ''
EXEC FMK.spAddLookup 'ColdDistributionTrigger', 4, N'حذف از دستگاه', 'Delete From Device', N'', N'', 'DST', 4, ''
EXEC FMK.spAddLookup 'ColdDistributionTrigger', 5, N'خاتمه در دستگاه', 'Finish In Device', N'', N'', 'DST', 5, ''
EXEC FMK.spAddLookup 'ColdDistributionTrigger', 6, N'باز كردن توزيع', 'Unlock Distribution', N'', N'', 'DST', 6, ''
EXEC FMK.spAddLookup 'ColdDistributionTrigger', 7, N'خاتمه توزيع', 'Dismiss', N'', N'', 'DST', 7, ''
EXEC FMK.spAddLookup 'ColdDistributionTrigger', 8, N'برگشت از خاتمه توزيع', 'Revoke Dismiss', N'', N'', 'DST', 8, ''
EXEC FMK.spAddLookup 'ColdDistributionTrigger', 9, N'برگشت از خاتمه توزيع', 'Revoke Dismiss', N'', N'', 'DST', 9, ''

EXEC FMK.spAddLookup 'ColdDistributionInvoiceState', 0, N'',			'',					N'', N'', 'DST', 0, ''
EXEC FMK.spAddLookup 'ColdDistributionInvoiceState', 1, N'تحول شد',		'Delivered',		N'', N'', 'DST', 1, ''
EXEC FMK.spAddLookup 'ColdDistributionInvoiceState', 2, N'تحويل نشد',	'Not Delivered',	N'', N'', 'DST', 2, ''

EXEC FMK.spAddLookup 'ColdDistributionReturnedInvoiceState', 0, N'',			'',				N'', N'', 'DST', 0, ''
EXEC FMK.spAddLookup 'ColdDistributionReturnedInvoiceState', 1, N'دريافت شد',	'Received',		N'', N'', 'DST', 1, ''
EXEC FMK.spAddLookup 'ColdDistributionReturnedInvoiceState', 2, N'دريافت نشد',	'Not Received',	N'', N'', 'DST', 2, ''

EXEC FMK.spAddLookup 'DebtCollectionListState', 0, N'',				'',				N'', N'', 'DST', 0, ''
EXEC FMK.spAddLookup 'DebtCollectionListState', 1, N'ثبت شده',		'Registered',	N'', N'', 'DST', 1, ''
EXEC FMK.spAddLookup 'DebtCollectionListState', 2, N'خاتمه يافته',	'Dismissed',	N'', N'', 'DST', 2, ''
EXEC FMK.spAddLookup 'DebtCollectionListState', 3, N'آماده وصول',	'Ready To Collect',	N'', N'', 'DST', 3, ''
EXEC FMK.spAddLookup 'DebtCollectionListState', 4, N'در حال وصول',	'Collecting',	    N'', N'', 'DST', 4, ''
EXEC FMK.spAddLookup 'DebtCollectionListState', 5, N'وصول شده', 	'Collected',	    N'', N'', 'DST', 5, ''

EXEC FMK.spAddLookup 'DebtCollectionListTrigger', 0, N'ثبت ليست وصول', 'Register Debt Collection List', N'', N'', 'DST', 0, ''
EXEC FMK.spAddLookup 'DebtCollectionListTrigger', 1, N'آماده وصول', 'Ready To Collect', N'', N'', 'DST', 1, ''
EXEC FMK.spAddLookup 'DebtCollectionListTrigger', 2, N'برگشت از آماده وصول', 'Return From Ready To Collect', N'', N'', 'DST', 2, ''
EXEC FMK.spAddLookup 'DebtCollectionListTrigger', 3, N'ارسال به دستگاه', 'Send To Device', N'', N'', 'DST', 3, ''
EXEC FMK.spAddLookup 'DebtCollectionListTrigger', 4, N'حذف از دستگاه', 'Delete From Device', N'', N'', 'DST', 4, ''
EXEC FMK.spAddLookup 'DebtCollectionListTrigger', 5, N'خاتمه در دستگاه', 'Finish In Device', N'', N'', 'DST', 5, ''
EXEC FMK.spAddLookup 'DebtCollectionListTrigger', 6, N'باز كردن ليست وصول', 'Unlock Debt Collection List', N'', N'', 'DST', 6, ''
EXEC FMK.spAddLookup 'DebtCollectionListTrigger', 7, N'خاتمه ليست وصول', 'Dismiss', N'', N'', 'DST', 7, ''
EXEC FMK.spAddLookup 'DebtCollectionListTrigger', 8, N'برگشت از خاتمه ليست وصول', 'Revoke Dismiss', N'', N'', 'DST', 8, ''
EXEC FMK.spAddLookup 'DebtCollectionListTrigger', 9, N'برگشت از خاتمه ليست وصول', 'Revoke Dismiss', N'', N'', 'DST', 9, ''

EXEC FMK.spAddLookup 'HotDistributionState', 0, N'',				'',				N'', N'', 'DST', 0, ''
EXEC FMK.spAddLookup 'HotDistributionState', 1, N'ثبت شده',		'Registered',	N'', N'', 'DST', 1, ''
EXEC FMK.spAddLookup 'HotDistributionState', 2, N'خاتمه يافته',	'Dismissed',	N'', N'', 'DST', 2, ''
EXEC FMK.spAddLookup 'HotDistributionState', 3, N'آماده توزيع',	'Ready To Distribute',	N'', N'', 'DST', 3, ''
EXEC FMK.spAddLookup 'HotDistributionState', 4, N'در حال توزيع',	'Distributing',	N'', N'', 'DST', 4, ''
EXEC FMK.spAddLookup 'HotDistributionState', 5, N'توزيع شده',	'Distributed',	N'', N'', 'DST', 5, ''

EXEC FMK.spAddLookup 'HotDistributionSaleDocumentType', 0, N'',				'',				N'', N'', 'DST', 0, ''
EXEC FMK.spAddLookup 'HotDistributionSaleDocumentType', 1, N'فاكتور',		'Invoice',	N'', N'', 'DST', 1, ''
EXEC FMK.spAddLookup 'HotDistributionSaleDocumentType', 2, N'فاكتور برگشتي',	'RetuenedInvoice',	N'', N'', 'DST', 2, ''

EXEC FMK.spAddLookup 'HotDistributionTrigger', 0, N'ثبت توزيع', 'Register Distribution', N'', N'', 'DST', 0, ''
EXEC FMK.spAddLookup 'HotDistributionTrigger', 1, N'صدور سند خروج انبار', 'Issue Inventory Delivery', N'', N'', 'DST', 1, ''
EXEC FMK.spAddLookup 'HotDistributionTrigger', 2, N'حذف سند خروج انبار', 'Delete Inventory Delivery', N'', N'', 'DST', 2, ''
EXEC FMK.spAddLookup 'HotDistributionTrigger', 3, N'ارسال به دستگاه', 'Send To Device', N'', N'', 'DST', 3, ''
EXEC FMK.spAddLookup 'HotDistributionTrigger', 4, N'حذف از دستگاه', 'Delete From Device', N'', N'', 'DST', 4, ''
EXEC FMK.spAddLookup 'HotDistributionTrigger', 5, N'خاتمه در دستگاه', 'Finish In Device', N'', N'', 'DST', 5, ''
EXEC FMK.spAddLookup 'HotDistributionTrigger', 6, N'باز كردن توزيع', 'Unlock Distribution', N'', N'', 'DST', 6, ''
EXEC FMK.spAddLookup 'HotDistributionTrigger', 7, N'خاتمه توزيع', 'Dismiss', N'', N'', 'DST', 7, ''
EXEC FMK.spAddLookup 'HotDistributionTrigger', 8, N'برگشت از خاتمه توزيع', 'Revoke Dismiss', N'', N'', 'DST', 8, ''
EXEC FMK.spAddLookup 'HotDistributionTrigger', 9, N'برگشت از خاتمه توزيع', 'Revoke Dismiss', N'', N'', 'DST', 9, ''