exec FMK.spAddKeyword 'Distribution.OrderOperations.DsOrder.List', N'فهرست درخواست هاي فروش، سفارش ها، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.OrderOperations.DsOrder.New', N'سفارش، ثبت سفارش', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.OrderOperations.DsOrderingFailure.List', N'فهرست عدم ثبت درخواستها، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.OrderOperations.DsOrderingFailure.New', N'ثبت عدم فعاليت', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.OrderOperations.DsReturnOrder.List', N'فهرست درخواست هاي برگشتي، مرجوعي ها، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.OrderOperations.DsReturnOrder.New', N'سفارش، مرجوعي كالا، برگشت', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.OrderOperations.DsReturnReason.List', N'فهرست علت برگشت كالا، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.OrderOperations.DsReturnReason.New', N'دليل برگشت كالا، برگشتي كالا', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.OrderOperations.DummyEntity.OrderingScheduling', N'برنامه ريزي، برنامه ريزي ويزيتور، زمانبندي مراجعه', N'', N'', N''
exec FMK.spAddKeyword 'Distribution.OrderOperations.Review', N'گزارش، گزارش توزيع، گزارش وصول', N'', N'', N''
