exec FMK.spAddKeyword 'FixedAsset.AssetManagement.Asset.List', N'كارت دارايي، انتقال، بلااستفاده، استفاده مجدد، فروش، اسقاط، حذف، مخارج پس از تحصيل، تغييرنرخ و روش', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DepreciationSummary.List', N' انباشته دارايي، حذف، صدور سند', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsAcquisitionReceipt.List', N'فهرست دارايي هاي تحصيل شده، بهره برداري، پلاك گذاري، ليست', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsAcquisitionReceipt.New', N'بهره برداري، تاسيس، تحويل گيرنده، جمعدار، پلاك گذاري، بهاي تمام شده، عمرمفيد، نرخ استهلاك، طول', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsChangeDepreciationMethod.List', N'فهرست تغيير نرخ و روش، ليست', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsChangeDepreciationMethod.New', N' تغيير روش محاسبه استهلاك دارايي', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsElimination.List', N'فهرست حذف دارايي، ليست', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsElimination.New', N'زيان ناشي از حذف، از بين رفتن، آتش سوزي، گم شدن', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsRepair.List', N'تعميرات اساسي، گسترش و الحاق، ليست', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsRepair.New', N'گسترش و الحاق دارايي، تعميرات اساسي', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsSale.List', N'فهرست فروش، ليست', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsSale.New', N'سود يا زيان', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsSalvage.List', N'فهرست اسقاط، ليست', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsSalvage.New', N'زيان', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsTransfer.List', N'فهرست انتقال دارايي، جابجايي، ليست', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsTransfer.New', N'جابجايي، تغيير تحويل گيرنده، تغيير محل استقرار، تغيير مركز هزينه', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsUnuseable.List', N'فهرست بلااستفاده، ليست', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.DsUseable.List', N'فهرست استفاده مجدد، ليست', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.Establishment', N'دارايي ثابت، شماره، ثبت پلاك قديم دارايي، بهاي تمام شده، استهلاك ', N'', N'', N''
exec FMK.spAddKeyword 'FixedAsset.AssetManagement.Review', N'گزارش، گردش، بهاي تمام شده، استهلاك ، ارزش اسقاط، فروش رفته، تحصيل، حذف، بلااستفاده، انتقال', N'', N'', N''
