exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryBalancing.List', N'فهرست انبارگرداني ها، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryBalancing.New', N'تگ، شمارش، كسر، اضافه، واقعي كردن موجودي، تعداد واقعي كالا', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryDelivery.List', N'فهرست حواله، مصرف مواد، انتقال بين انبارها، جابجايي انبارها، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryDelivery.New', N'حواله، حواله فاكتور، تحويل كالا، خروج مواد اوليه، مصرف، انتقال بين انبار، جابجايي، فروش', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryDeliveryReturn.List', N'فهرست حواله برگشت، تحويل كالا، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryDeliveryReturn.New', N'برگشتي كالا، حواله برگشتي، فروش، تحويل', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryPricing.List', N'حذف قيمت گذاري انبار، حواله ها، خروج ها ، ريال انبار', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryPricing.New', N'ميانگين موزون، بهاي تمام شده كالاي فروش رفته، محاسبه ميانگين، حواله، خروج، ريالي كردن', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryPurchaseInvoice.List', N'فهرست فاكتور خريد، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryPurchaseInvoice.New', N'فاكتور خريد كالا، سفارش خريد', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryReceipt.List', N'فهرست رسيد انبار، ورود، خريد، توليد، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryReceipt.New', N'قبض انبار،ورود كالا، واردات، خارجي، ثبت سفارش، هزينه حمل، قبض توليد، موجودي اول دوره، رسيد انتقالي، ارزش افزوده خريد', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryReceiptReturn.List', N'فهرست مرجوعي كالا، كالاهاي مرجوع شده، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DsInventoryReceiptReturn.New', N'برگشت خريد، قبض برگشتي، عودت كالا، مرجوع، برگشت قبض انبار، برگشت از توليد', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DummyEntity.InventoryPriceReview', N'گزارش، كالا، گردش، رديابي، ريز خريد، ريز توليد، كاردكس، مانده، موجودي، خالص', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DummyEntity.ItemCardex', N'كاردكس رديابي', N'', N'', N''
exec FMK.spAddKeyword 'Inventory.InventoryOperations.DummyEntity.ProductionPricing', N'رسيد توليد، سفارشات، تعيين بهاي تمام شده كالاي ساخته شده، توليد، ريالي كردن توليد', N'', N'', N''
