DELETE FROM FMK.Lookup WHERE [Type] = 'MarketingDisketteType1396'

exec FMK.spAddLookup 'MarketingDisketteType1396',1,N'خريد','Buy',N'كڕين',N'الشراء','GNR',1,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',2,N'فروش','Sale',N'فرۆش',N'مبيعات','GNR',2,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',3,N'خريد و فروش','Buy And Sales',N'كڕين و فرۆش',N'الشراء و مبيعات','GNR',3,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',4,N'صورت وضعيت','Status',N'پوختەي هەلومەرج',N'بيان الايصال','GNR',4,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',5,N'خريد و صورت وضعيت','Buy And Status',N'كڕين و پوختەي هەلومەرج',N'الشراء و بيان الايصال','GNR',5,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',6,N'فروش و صورت وضعيت','Sales And Status',N'فرۆش و پوختەي هەلومەرج',N'مبيعات و بيان الايصال','GNR',6,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',7,N'خريد و فروش و صورت وضعيت','Buy And Sales And Status',N'كڕين و فرۆش و پوختەي هەلومەرج',N'الشراء و مبيعات و بيان الايصال','GNR',7,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',8,N'خريد وارداتي','ImportBuy',N'ImportBuy',N'ImportBuy','GNR',8,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',9,N'خريد و خريد وارداتي','Buy And ImportBuy',N'كڕين و ImportBuy',N'الشراء و ImportBuy','GNR',9,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',10,N'فروش و خريد وارداتي','Sales And ImportBuy',N'فرۆش و ImportBuy',N'مبيعات و ImportBuy','GNR',10,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',11,N'خريد و فروش و خريد وارداتي','Buy And Sales And ImportBuy',N'كڕين و فرۆش و ImportBuy',N'الشراء و مبيعات و ImportBuy','GNR',11,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',12,N'صورت وضعيت و خريد وارداتي','Status And ImportBuy',N'پوختەي هەلومەرج و ImportBuy',N'بيان الايصال و ImportBuy','GNR',12,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',13,N'خريد و صورت وضعيت و خريد وارداتي','Buy And Status And ImportBuy',N'كڕين و پوختەي هەلومەرج و ImportBuy',N'الشراء و بيان الايصال و ImportBuy','GNR',13,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',14,N'فروش و صورت وضعيت و خريد وارداتي','Sales And Status And ImportBuy',N'فرۆش و پوختەي هەلومەرج و ImportBuy',N'مبيعات و بيان الايصال و ImportBuy','GNR',14,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',15,N'خريد و فروش و صورت وضعيت و خريد وارداتي','Buy And Sales And Status And ImportBuy',N'كڕين و فرۆش و پوختەي هەلومەرج و ImportBuy',N'الشراء و مبيعات و بيان الايصال و ImportBuy','GNR',15,''  

exec FMK.spAddLookup 'MarketingDisketteType1396',16,N'صورت وضعيت پيمانكاري جزء','StatusOwnerShip',N'',N'','GNR',16,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',17,N'خريد و صورت وضعيت پيمانكاري جزء','Buy And StatusOwnerShip',N'',N'','GNR',17,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',18,N'فروش و صورت وضعيت پيمانكاري جزء','Sale And StatusOwnerShip',N'',N'','GNR',18,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',19,N'خريد و فروش و صورت وضعيت پيمانكاري جزء','Buy And Sale And StatusOwnerShip',N'',N'','GNR',19,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',20,N'صورت وضعيت  پيمانكار و پيمانكار جزء','Status And StatusOwnerShip',N'',N'','GNR',20,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',21,N'خريد و صورت وضعيت  پيمانكار و پيمانكار جزء','Buy And Status And StatusOwnerShip',N'',N'','GNR',21,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',22,N'فروش و صورت وضعيت  پيمانكار و پيمانكار جزء','Sale And Status And StatusOwnerShip',N'',N'','GNR',22,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',23,N'خريد و فروش و صورت وضعيت  پيمانكار و پيمانكار جزء','Buy And Sale And Status And StatusOwnerShip',N'',N'','GNR',23,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',24,N'خريد وارداتي و صورت وضعيت پيمانكار جزء','Import And Status And StatusOwnerShip',N'',N'','GNR',24,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',25,N'خريد و خريد وارداتي و صورت وضعيت پيمانكار جزء','Buy and Import And StatusOwnerShip',N'',N'','GNR',25,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',26,N'فروش و خريد وارداتي و صورت وضعيت پيمانكار جزء','Sale And Import And StatusOwnerShip',N'',N'','GNR',26,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',27,N'خريد و فروش و خريد وارداتي و صورت وضعيت پيمانكار جزء','Buy And Sale And Import And StatusOwnerShip',N'',N'','GNR',27,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',28,N'صورت وضعيت و خريد وارداتي و صورت وضعيت پيمانكار جزء','Status And Import And StatusOwnerShip',N'',N'','GNR',28,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',29,N'خريد و صورت وضعيت و خريد وارداتي و صورت وضعيت پيمانكار جزء','Buy And Status And Import And StatusOwnerShip',N'',N'','GNR',29,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',30,N'فروش و صورت وضعيت و خريد وارداتي و صورت وضعيت پيمانكار جزء','Sale And Status And Import And StatusOwnerShip',N'',N'','GNR',30,''  
exec FMK.spAddLookup 'MarketingDisketteType1396',31,'همه','All',N'هه‌موو',N'كل','GNR',31,''

exec FMK.spAddLookup 'CustomerCategoryForTax96', 0, N'هيچكدام' , '' , '' , '' , 'GNR', 0,''
exec FMK.spAddLookup 'CustomerCategoryForTax96', 5, N'مودي مشمول ثبت نام در نظام مالياتي' , '' , '' , '' , 'GNR', 1,''
exec FMK.spAddLookup 'CustomerCategoryForTax96', 6, N'مشمولين حقيقي ماده 81' , '' , '' , '', 'GNR', 2, ''
exec FMK.spAddLookup 'CustomerCategoryForTax96', 7, N'اشخاصي كه مشمول ثبت نام در نظام مالياتي نيستند' , '' , '' , '', 'GNR', 3, ''
exec FMK.spAddLookup 'CustomerCategoryForTax96', 8, N'مصرف كننده نهايي' , '' , '' , '', 'GNR', 4, ''

exec FMK.spAddLookup 'VendorCategoryForTax96', 0, N'هيچكدام' , '' , '' , '' , 'GNR', 0,''
exec FMK.spAddLookup 'VendorCategoryForTax96', 5, N'مودي مشمول ثبت نام در نظام مالياتي' , '' , '' , '' , 'GNR', 1,''
exec FMK.spAddLookup 'VendorCategoryForTax96', 6, N'مشمولين حقيقي ماده 81' , '' , '' , '', 'GNR', 2, ''
exec FMK.spAddLookup 'VendorCategoryForTax96', 7, N'اشخاصي كه مشمول ثبت نام در نظام مالياتي نيستند' , '' , '' , '', 'GNR', 3, ''
exec FMK.spAddLookup 'VendorCategoryForTax96', 8, N'كمتر از 5 % حد نصاب' , '' , '' , '', 'GNR', 4, ''

exec FMK.spAddLookup 'CompanyCitizenship', 0, N'ايراني' , '' , '' , '', 'GNR', 0, ''
exec FMK.spAddLookup 'CompanyCitizenship', 1, N'خارجي' , '' , '' , '', 'GNR', 1, ''


exec FMK.spAddLookup 'MarketingDisketteItemType1396',1,'فاكتور','Invoice',N'پسولە',N'الفاتورة','GNR',1,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',2,'رسيد انبار','Invoice',N'رەسيدي كۆگا',N'ايصالات المخزون','GNR',2,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',3,'فاكتور برگشتي','Returned Invoice',N'گەرانەوەي پسولە',N'فاتورة العودة','GNR',3,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',4,'برگشت رسيد','Invoice',N'گەڕانەوەي رەسيد',N'عودة الايصال','GNR',4,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',5,'فاكتور خريد خدمات','Service Inventory Purchase Invoice',N'پسولەي كڕيني خزمەتگوزارييەكان',N'فاتورة خدمات ترتيب','GNR',5,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',6,'صورت وضعيت','Status',N'پوختەي هەلومەرج',N'الفاتورة','GNR',6,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',7,'حمل رسيد انبار','InventoryReceiptTransport',N'',N'','GNR',7,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',8,'فاكتور فروش صادراتي','Export Sale Invoice',N'',N'','GNR',8,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',9,'فاكتور برگشتي صادراتي','Export Sale Returned Invoice',N'',N'','GNR',9,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',10,'رسيد انبار وارداتي','Import Inventory Receipt',N'',N'','GNR',10,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',11,'برگشت رسيد انبار وارداتي','Import Inventory Returned Receipt',N'',N'','GNR',11,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',12,'فاكتور خريد دارايي','Asset Purchase Invoice',N'',N'','GNR',12,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',13,'فروش دارايي','AssetSale',N'',N'','GNR',13,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',17,'ترخيص','CustomsClearance',N'',N'','GNR',17,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',18,'بارنامه','BillOfLoading',N'',N'','GNR',18,''
exec FMK.spAddLookup 'MarketingDisketteItemType1396',19,'بيمه نامه','InsurancePolicy',N'',N'','GNR',19,''



exec FMK.spAddLookup 'ItemCategoryForTax96', 1, N'دارو' , 'Medicine' , '' , '' , 'GNR', 0,''
exec FMK.spAddLookup 'ItemCategoryForTax96', 2, N'دخانيات' , 'Tobacco' , '' , '' , 'GNR', 1,''
exec FMK.spAddLookup 'ItemCategoryForTax96', 3, N'موبايل' , 'Mobile' , '' , '', 'GNR', 2, ''
exec FMK.spAddLookup 'ItemCategoryForTax96', 4, N'لوازم خانگي برقي' , 'Household Appliances' , '' , '', 'GNR', 3, ''
exec FMK.spAddLookup 'ItemCategoryForTax96', 5, N'قطعات مصرفي و يدكي وسايل نقليه' , 'Spare parts for vehicles' , '' , '', 'GNR', 4, ''
exec FMK.spAddLookup 'ItemCategoryForTax96', 6, N'فراورده ها و مشتقات نفتي و گازي و پتروشيميايي' , 'Oil and Gas and Petrochemical Products and Derivatives' , '' , '' , 'GNR', 5,''
exec FMK.spAddLookup 'ItemCategoryForTax96', 7, N'طلا اعم از شمش ،مسكوكات و مصنوعات زينتي' , 'Gold, including billets, brooches and ornamental artifacts' , '' , '' , 'GNR', 6,''
exec FMK.spAddLookup 'ItemCategoryForTax96', 8, N'منسوجات و پوشاك' , 'Textiles and clothing' , '' , '', 'GNR', 7, ''
exec FMK.spAddLookup 'ItemCategoryForTax96', 9, N'اسباب بازي' , 'toy' , '' , '', 'GNR', 8, ''
exec FMK.spAddLookup 'ItemCategoryForTax96', 10, N'دام زنده، گوشت سفيد و قرمز' , 'Livestock, white and red meat' , '' , '', 'GNR', 9, ''
exec FMK.spAddLookup 'ItemCategoryForTax96', 11, N'محصولات اساسي كشاورزي' , 'Basic agricultural products' , '' , '', 'GNR', 10, ''
exec FMK.spAddLookup 'ItemCategoryForTax96', 12, N'ساير كالا ها و خدمات' , 'Other items and services' , '' , '', 'GNR', 11, ''

 
 