exec FMK.spAddLookup 'AddressType',1,'محل فعاليت','Business',N'شوێني چالاكي',N'مكان للنشط','GNR',1,''
exec FMK.spAddLookup 'AddressType',2,'ارسال صورتحساب','Bill',N'ناردني ليستي ژمێرە',N'ارسال ايصال الفواتير','GNR',2,''
exec FMK.spAddLookup 'AddressType',3,'ارسال كالا','Shipping',N'ناردني كەرەستە',N'ارسال البضائع','GNR',3,''
exec FMK.spAddLookup 'AddressType',4,'انبار','Warehouse',N'كۆگا',N'المستودع','GNR',4,''
exec FMK.spAddLookup 'AddressType',5,'منزل','Home',N'خانوو',N'بيت','GNR',5,''
exec FMK.spAddLookup 'AddressType',6,'رسمي','Official',N'رەسمي',N'الرسمي','GNR',6,''
exec FMK.spAddLookup 'AddressType',7,'پستي','Postal',N'پۆستيي',N'بريدي','GNR',7,''
exec FMK.spAddLookup 'AddressType',8,'ساير','Misc.',N'ديكە',N'الآخر','GNR',8,''

exec FMK.spAddLookup 'PartyType',1,'شخص حقيقي','Individual',N'كەسي حەقێقي',N'الشخص الحقيقي','GNR',1,''
exec FMK.spAddLookup 'PartyType',2,'شخص حقوقي','Company',N'كەسي حقۆقي',N'كيان قانوني','GNR',2,''

exec FMK.spAddLookup 'PartySubType',1,'وزارتخانه','Ministry',N'وەزارەتخانە',N'وزارة','GNR',1,''
exec FMK.spAddLookup 'PartySubType',2,'موسسه دولتي','Governmental institutions',N'رێكخراوەي حكوومي',N'مؤسسة حكومية','GNR',2,''
exec FMK.spAddLookup 'PartySubType',3,'شركت دولتي','Governmental Company',N'كۆمپانياي حكوومي',N'الشركة الحومية','GNR',3,''
exec FMK.spAddLookup 'PartySubType',4,'ساير دستگاه هاي دولتي','Other governmental units',N'فەرمانگەكاني‌تري حكوومي',N'نظامات حكومية أخرى','GNR',4,''
exec FMK.spAddLookup 'PartySubType',5,'نهادهاي عمومي غير دولتي','Non-governmental public institutions',N'رێكخراوە گشتيە ناحكووميەكان',N'الهيئات العامة و المنظمات غير الحكومية','GNR',5,''
exec FMK.spAddLookup 'PartySubType',6,'بخش خصوصي','Private Sector',N'بەشي ئەهلي',N'قطاع خاص','GNR',6,''
exec FMK.spAddLookup 'PartySubType',7,'ساير','Others',N'ديكە',N'الآخر','GNR',7,''

exec FMK.spAddLookup 'PhoneType',1,'تلفن دفتر','Office Phone',N'تەلەفووني نووسينگە',N'هاتف المكتب','GNR',1,''
exec FMK.spAddLookup 'PhoneType',2,'تلفن همراه','Mobile',N'ژمارە مۆبايل',N'الهواتف المحمولة','GNR',2,''
exec FMK.spAddLookup 'PhoneType',3,'تلفن منزل','Home Phone',N'تەلەفووني ماڵ',N'هاتف البيت','GNR',3,''
exec FMK.spAddLookup 'PhoneType',4,'تلفن ساير','Misc. Phone',N'تەلەفوونەكاني‌تر',N'الهاتف أخرى','GNR',4,''
exec FMK.spAddLookup 'PhoneType',5,'دورنگار دفتر','Office Fax',N'فكسي نووسينگە',N' الفاكس للمكتب','GNR',5,''
exec FMK.spAddLookup 'PhoneType',6,'دورنگار منزل','Home Fax',N'فكسي ماڵ',N' الفاكس للبيت','GNR',6,''
exec FMK.spAddLookup 'PhoneType',7,'دورنگار ساير','Misc. Fax',N'فكسەكاني‌تر',N'الفاكس الآخر','GNR',7,''

exec FMK.spAddLookup 'PartyOpeningBalanceType',0,'مشتري','Customer',N'كڕيار',N'زبون','GNR',0,''
exec FMK.spAddLookup 'PartyOpeningBalanceType',1,'تامين كننده','Vendor',N'دابينكار',N'المزود','GNR',1,''
exec FMK.spAddLookup 'PartyOpeningBalanceType',2,'واسط','Broker',N'',N'','GNR',2,''

exec FMK.spAddLookup 'CustomerCategoryForTax', 1, 'فروش توسط ماشينهاي فروش Pos', 'FinalConsumer',N'فرۆش لە لايەن ماشێنەكاني فرۆشەوە',N' البيع من قبل آلات البيع', 'GNR', 1, ''
exec FMK.spAddLookup 'CustomerCategoryForTax', 2, 'عادي', 'Normal',N'ئاسايي',N'عادي', 'GNR', 2, ''
exec FMK.spAddLookup 'CustomerCategoryForTax', 3, 'طرف معامله خارجي كه در ايران اقامت و فعاليت اقتصادي ندارند', 'Export',N'لايەني مامەڵەي دەرەكي كە لە ئێراند مۆڵەت و چالاكي ئابوورييان نييە',N'جانب الصفقة الخارجية الذي ليست لهم أنشطة التجارة الخارجية والاقتصادية  في إيران', 'GNR', 3, ''

exec FMK.spAddLookup 'CreditCheckingType', 1, 'هشدار در صورت بيشتر شدن مانده از اعتبار', 'Warning', N'', N' التحذير في حالة ازدياد البقية من ائتمان الحساب','GNR', 1, ''
exec FMK.spAddLookup 'CreditCheckingType', 2, 'جلوگيري از عمليات در صورت بيشتر شدن مانده از اعتبار', 'Deny', N'', N'منع العملية  في حالة ازدياد البقية من ائتمان الحساب', 'GNR', 2, ''
exec FMK.spAddLookup 'CreditCheckingType', 3, 'هيچكدام', 'None',N'',N'لا شيء', 'GNR',3, ''
