exec FMK.spAddKeyword 'Payroll.PayrollOperation.DsMonthlyData.New', N'عملكرد، ريز كاركرد، ثبت مرخصي، پاداش ', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.PayrollOperation.DsSettlement.New', N'پرسنل، ترك كار، پايان كار، پايان قرارداد، تسويه كارمند', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.PayrollOperation.DummyEntity.BankDisk', N'ليست پرداخت گروهي، ديسكت، ديسكت پرداخت بانك، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.PayrollOperation.DummyEntity.Calculation', N'فيش حقوق، عيدي، مرخصي، ذخيره سنوات، محاسبات ماهانه، بازخريد مرخصي', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.PayrollOperation.DummyEntity.EditLeave', N'تغيير مانده، ويرايش، سوخت', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.PayrollOperation.DummyEntity.InsuranceDisk', N'حق بيمه پرسنل، تامين اجتماعي، فايل بيمه', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.PayrollOperation.DummyEntity.PayrollLists', N'گزارشات حقوق', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.PayrollOperation.DummyEntity.PayrollReview', N'گزارش، جزئيات محاسبات، جزئيات محاسبه حقوق', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.PayrollOperation.DummyEntity.TaxDisk', N'فايل الكترونيك ماليات بر درامد حقوق، Salary، فايل ماليات بر درآمد پرسنل', N'', N'', N''
