exec FMK.spAddKeyword 'Payroll.BasicData.DsBranch.New', N'بيمه تامين اجتماعي، بيمه تكميلي، دارايي', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DsElement.List', N'فهرست عوامل حقوق، مزاياي پرسنل، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DsElement.New', N'عوامل قرارداد، پرداختي به پرسنل، مزايا، كسور، تعهدات كارفرما، كاركرد، روزانه، ساعتي', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DsJob.List', N'فهرست شغل، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DsJob.New', N'سمت، كار، پيشه كارمند، كد شغل بيمه', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DsLoan.List', N'فهرست وام هاي تعريف شده، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DsLoan.New', N'تعريف وام كارمندي، انواع وام كارمندي', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DsTaxTable.List', N'فهرست جداول مالياتي، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DsTaxTable.New', N'قانون ماليات حقوق، پله هاي معافيت مالياتي', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DsWorksite.List', N'فهرست محل خدمت، فعاليت، اشتغال، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DsWorksite.New', N'محل فعاليت، محل اشتغال', N'', N'', N''
exec FMK.spAddKeyword 'Payroll.BasicData.DummyEntity.ElementControl', N'فرمول دهي، فرمول محاسبه، نحوه، عامل ماليات پذير، بيمه پذير', N'', N'', N''
