exec FMK.spAddLookup 'TaxPaymentType',1,'نقدي','Cash',N'نەختيي',N'النقد','PAY',1,''
exec FMK.spAddLookup 'TaxPaymentType',2,'غيرنقدي','Non-Cashe',N'غەيرە نەختي',N'غير النقدية','PAY',2,''
exec FMK.spAddLookup 'TaxPaymentType',3,'ارائه ليست بدون پرداخت','List without payment',N'پێشكەش كردني ليست بەبێ پێدان',N'تقديم القائمة من دون دفع الأجر','PAY',3,''
exec FMK.spAddLookup 'TaxPaymentType',4,'چك شخصي','Personal Check',N' ',N'شيك شخصي','PAY',4,''
exec FMK.spAddLookup 'TaxPaymentType',5,'پرداخت با كارت اعتباري','POS(Payment Card)',N' ',N'تسديد عن طريق بطاقة الائتمان','PAY',5,''
exec FMK.spAddLookup 'TaxPaymentType',6,'انتقال بانكي','Bank Transfer',N' ',N'حوالة مصرفية','PAY',6,''
exec FMK.spAddLookup 'TaxPaymentType',7,'سفته','Promissory Note',N' ',N'إذني','PAY',7,''
exec FMK.spAddLookup 'TaxPaymentType',8,'چك تضمين شده','Gauranteed Check/Certified Check',N' ',N'شيك مضمون','PAY',8,''
exec FMK.spAddLookup 'TaxPaymentType',9,'واريز خزانه','Treasury',N' ',N'إيداع الخزانة','PAY',9,''

exec FMK.spAddLookup 'TaxBankType',100,' ',' ','',N'','PAY',0,''
exec FMK.spAddLookup 'TaxBankType',0,'ساير','Other',N'ديكە',N'ساير','PAY',100,''
exec FMK.spAddLookup 'TaxBankType',1,'بانك ملي','Melli',N'بانكي ميللي',N'البنك ملي','PAY',1,''
exec FMK.spAddLookup 'TaxBankType',2,'بانك صادرات','Saderat',N'بانكي سادرات',N'بنك صادرات','PAY',2,''
exec FMK.spAddLookup 'TaxBankType',3,'بانك ملت','Mellat',N'بانكي ميللەت',N'بنك ملت','PAY',3,''
exec FMK.spAddLookup 'TaxBankType',4,'بانك سپه','Sepah',N'بانكي سپە',N'بنك سبه','PAY',4,''
exec FMK.spAddLookup 'TaxBankType',5,'بانك كشاورزي','Keshavarzi',N'بانكي كشاورزي',N'البنك كشاورزي','PAY',5,''
exec FMK.spAddLookup 'TaxBankType',6,'بانك رفاه كارگران','Refah',N'بانكي رفا كارگران',N'بنك رفاه كارگران','PAY',6,''
exec FMK.spAddLookup 'TaxBankType',7,'بانك توسعه صادرات','Tosee Saderat',N'بانكي تۆسعەي سادرات',N'بنك تنمية الصادرات','PAY',7,''
exec FMK.spAddLookup 'TaxBankType',8,'بانك مسكن','Maskan',N'بانكي مەسكەن',N'بنك  مسكن','PAY',8,''
exec FMK.spAddLookup 'TaxBankType',9,'بانك تجارت','Tejarat',N'بانكي تجارەت',N'بنك التجارة','PAY',9,''
exec FMK.spAddLookup 'TaxBankType',10,'بانك پارسيان','Parsian',N'بانكي پارسيان',N'البنك بارسيان','PAY',10,''
exec FMK.spAddLookup 'TaxBankType',11,'بانك اقتصاد نوين','Eghtesad Novin',N'بانكي اقتسادي نوين',N'بنك الاقتصاد النوين','PAY',11,''
exec FMK.spAddLookup 'TaxBankType',12,'بانك پاسارگاد','Pasargad',N'بانكي پاسارگاد',N'البنك باسارغاد','PAY',12,''
exec FMK.spAddLookup 'TaxBankType',13,'بانك سرمايه','Sarmaie',N'بانكي سەرمايە',N'بنك سرماية','PAY',13,''
exec FMK.spAddLookup 'TaxBankType',14,'بانك سامان','Saman',N'بانكي سامان',N'بنك سامان','PAY',14,''
exec FMK.spAddLookup 'TaxBankType',15,'بانك صنعت و معدن','Sanat o Madan',N'بانكي سەنعەت و مەعدەن',N'بنك الصناعة و المعادن','PAY',15,''
exec FMK.spAddLookup 'TaxBankType',16,'بانك پست بانك','Post Bank',N'بانكي پۆست بانك',N'بنك بريد البنك','PAY',16,''
exec FMK.spAddLookup 'TaxBankType',17,'بانك كارآفرين','Kar Afrain',N'بانكي كارافەرين',N'بنك كارآفرين','PAY',17,''


exec FMK.spAddLookup 'CalculationType',1,'محاسبات ماهانه','MonthlyCalculation',N'ژمێرياري مانگانە',N'الحسابات الشهرية','PAY',1,''
exec FMK.spAddLookup 'CalculationType',2,'ذخيره سنوات','WorkingHistorySaving',N'پاشەكەوتي ساڵەكان',N'تخزين السنوات','PAY',2,''
exec FMK.spAddLookup 'CalculationType',3,'بازخريد سنوات','WorkingHistoryRepayment',N'كڕينەوەي ساڵەكان',N'استرداد شراء السنوات  ','PAY',3,''
exec FMK.spAddLookup 'CalculationType',4,'ذخيره مرخصي','LeaveSaving',N'پاشەكەوتي مۆڵەت',N'تخزين الإجازة','PAY',4,''
exec FMK.spAddLookup 'CalculationType',5,'بازخريد مرخصي','LeaveRepayment',N'كڕينەوەي مۆڵەت',N'استرداد شراء الإجازة','PAY',5,''
exec FMK.spAddLookup 'CalculationType',6,'پرداخت عيدي','NewYearBonus',N'پێداني جێژنانە',N'أجور العيد','PAY',6,''

exec FMK.spAddLookup 'PayrollSettlementItemType',1,'مطالبه','Claim',N'داواكاري',N'الطلب','PAY',1,''
exec FMK.spAddLookup 'PayrollSettlementItemType',2,'بدهي','Debt',N'قەرز',N'دين','PAY',2,''
