exec FMK.spAddKeyword 'ReceiptAndPayment.BasicData.DsBankAccount.List', N'فهرست حسابهاي بانكي، تفصيل، ليست', N'', N'', N''
exec FMK.spAddKeyword 'ReceiptAndPayment.BasicData.DsBankAccount.New', N'تعريف شماره حساب، تفصيل بانك', N'', N'', N''
exec FMK.spAddKeyword 'ReceiptAndPayment.BasicData.DsCash.List', N'فهرست صندوق، تفصيل، ليست', N'', N'', N''
exec FMK.spAddKeyword 'ReceiptAndPayment.BasicData.DsCash.New', N'تفصيل', N'', N'', N''
exec FMK.spAddKeyword 'ReceiptAndPayment.BasicData.DsChequeBook.List', N'فهرست دسته چك ها، ليست', N'', N'', N''
exec FMK.spAddKeyword 'ReceiptAndPayment.BasicData.DsChequeBook.New', N'بانكي', N'', N'', N''
exec FMK.spAddKeyword 'ReceiptAndPayment.BasicData.DsPos.List', N'فهرست دستگاه كارتخوان، ليست', N'', N'', N''
exec FMK.spAddKeyword 'ReceiptAndPayment.BasicData.DsPos.New', N'كارتخوان متصل به حساب بانك، دستگاه پوز، پوز بانكي', N'', N'', N''
exec FMK.spAddKeyword 'ReceiptAndPayment.BasicData.DsPettyCash.New', N'تنخواه گردان، تنخواه دار، تنخواه، مسئول تنخواه', N'', N'', N''
exec FMK.spAddKeyword 'ReceiptAndPayment.BasicData.DsPettyCash.List', N'فهرست تنخواه گردان، فهرست تنخواه دار، فهرست تنخواه، فهرست مسئول تنخواه', N'', N'', N''
