exec FMK.spAddLookup 'ReceiptBanking',1,'واگذار به بانك','Transfer To Bank',N'رادەست‌كار بە بانك',N'تعيين للبنك','RPA',1,''
exec FMK.spAddLookup 'ReceiptBanking',2,'وصول و واخواست','Cashing and Return',N'وەرگرتن و پێشبڕي',N'استلام و الاحتجاج','RPA',2,''
exec FMK.spAddLookup 'ReceiptBanking',3,'نقد كردن','Cashing',N'نەختەوە كردن',N'النقدية','RPA',3,''

exec FMK.spAddLookup 'ReceiptChequeState',1,'نزد صندوق','InCash',N'لە لاي بوخچەوە',N'صندوق','RPA',1,''
exec FMK.spAddLookup 'ReceiptChequeState',2,'واگذار به بانك','Tranfer To Bank',N'رادەست‌كار بە بانك',N'تعيين للبنك','RPA',2,''
exec FMK.spAddLookup 'ReceiptChequeState',4,'وصول','Cashed',N'وەرگرتن',N'الجمع','RPA',3,''
exec FMK.spAddLookup 'ReceiptChequeState',8,'واخواست','Returned',N'پێشبڕيي',N'احتجاج','RPA',4,''
exec FMK.spAddLookup 'ReceiptChequeState',16,'نقد شده','Cashed',N'نەختەوەكراو',N'النقدية','RPA',5,''
exec FMK.spAddLookup 'ReceiptChequeState',32,'خرج شده','Spending',N'خەرج كراو',N'خرج شده','RPA',6,''
exec FMK.spAddLookup 'ReceiptChequeState',64,'استرداد','Refunded',N'گێڕانەوە',N'الردّ','RPA',7,''

exec FMK.spAddLookup 'ReceiptItemType',1,'وجه نقد','Cash',N'پارەي نەخت',N'نقد','RPA',1,''
exec FMK.spAddLookup 'ReceiptItemType',2,'كارت خوان','Card Reader',N'كارت‌ناس',N'بطاقة قارئ','RPA',2,''
exec FMK.spAddLookup 'ReceiptItemType',4,'چك','Cheque',N'چەك',N'الشيك','RPA',3,''
exec FMK.spAddLookup 'ReceiptItemType',8,'حواله','Draft',N'حەواڵە',N'مسودة','RPA',4,''
exec FMK.spAddLookup 'ReceiptItemType',16,'تنخواه دار','Petty Cash',N'',N'','RPA',5,''

exec FMK.spAddLookup 'ReceiptType',1,'دريافت از مشتري','Customer Receipt',N'وەرگرتن لە كڕيار',N'التلقي من الزبون','RPA',1,''
exec FMK.spAddLookup 'ReceiptType',2,'ساير دريافت ها','Other Receipt',N'وەرگرتنەكاني‌تر',N'الاستلامات الأخرى','RPA',4,''
exec FMK.spAddLookup 'ReceiptType',4,'تضمين','Guarantee',N'مسۆگەر',N'ضمان','RPA',5,''
exec FMK.spAddLookup 'ReceiptType',8,'دريافت از واسط','BrokerReceipt',N'',N'','RPA',3,''
exec FMK.spAddLookup 'ReceiptType',16,'دريافت از تامين كننده','Vendor Receipt',N'وەرگرتن لە دابينكار',N'التلقي من الموردين','RPA',2,''
exec FMK.spAddLookup 'ReceiptType',32,'انتقالي','Transmit Receipt',N'گوێزراوەيي',N'النقلي','RPA',6,''
exec FMK.spAddLookup 'ReceiptType',64,'دريافت از تنخواه دار','PettyCash Receipt',N'',N'','RPA',7,''

exec Fmk.spAddLookup 'CashFlowReportType',1,'1: موجودي بانك','1: Bank Balanace',N'1: هەبووي بانك',N'1: الممتلكات و لأموال النقدية للمصرف','RPA',1,''
exec Fmk.spAddLookup 'CashFlowReportType',2,'2: موجودي صندوق','2: Cash Balance',N'هەبووي بوخچە:2',N'2: أموال','RPA',2,''
exec Fmk.spAddLookup 'CashFlowReportType',3,'3: موجودي دستگاه كارت خوان','3: Pos Balance',N'هەبووي ئامێري كارت‌ناس:3',N'3: قارئ بطاقة المخزون','RPA',3,''
exec Fmk.spAddLookup 'CashFlowReportType',4,'4: چكهاي دريافتني نزد صندوق','4: Recievable Cheques in Cash',N'ئەو چەكانەي لاي بوخچە كە دەبێ وەربگيردرێت:4',N'4: الشيكات المستحقة من الصندوق','RPA',4,''
exec Fmk.spAddLookup 'CashFlowReportType',5,'5: چكهاي دريافتني نزد بانك','5: Recievable Cheques in Bank',N'ئەو چەكانەي لاي بانك كە دەبێ وەربگيردرێت:5',N'5: الشيكات المستحقة للبنك','RPA',5,''
exec Fmk.spAddLookup 'CashFlowReportType',6,'6: چكهاي پرداختني وصول نشده','6: Payable Cheques',N'ئەو چەكە پێدراوانە كە نەختەوە نەكراون:6', N'6- الشيكات المستحقة غير المسددة','RPA',6,''
exec Fmk.spAddLookup 'CashFlowReportType',7,'7: تعهدات دريافتني','7: Recievable',N'بەڵێنەكان بۆ وەرگرتن:7',N'7: التعهدات المستحقة','RPA',7,''
exec Fmk.spAddLookup 'CashFlowReportType',8,'8: تعهدات پرداختني','8: Payable',N'بەڵێنەكان بۆ پێدان:8',N'8: الالتزامات المستحقة','RPA',8,''

