exec FMK.spAddLookup 'LineStyle',0,'_____________','Solid','',N'_____________','GNR',0,''
exec FMK.spAddLookup 'LineStyle',1,'---.--.--.-.-.---.-------','Dash','',N'_____________','GNR',1,''
exec FMK.spAddLookup 'LineStyle',2,'-------------------','Dot','-------------------',N'-------------------','GNR',2,''
exec FMK.spAddLookup 'LineStyle',3,'-------------------','DashDot','-------------------',N'-------------------','GNR',3,''
exec FMK.spAddLookup 'LineStyle',4,'-------------------','DashDotDot','-------------------',N'-------------------','GNR',4,''
exec FMK.spAddLookup 'LineStyle',5,'-------------------','Double','-------------------',N'-------------------','GNR',5,''

exec FMK.spAddLookup 'PaperSize',1,'Custom','Custom','Custom',N'Custom','GNR',1,''
exec FMK.spAddLookup 'PaperSize',2,'Letter','Letter','Letter',N'Letter','GNR',2,''
exec FMK.spAddLookup 'PaperSize',3,'Tabloid','Tabloid','Tabloid',N'Tabloid','GNR',3,''
exec FMK.spAddLookup 'PaperSize',4,'Leggal','Leggal','Leggal',N'Leggal','GNR',4,''
exec FMK.spAddLookup 'PaperSize',5,'A3','A3','A3',N'A3','GNR',5,''
exec FMK.spAddLookup 'PaperSize',6,'A4','A4','A4',N'A4','GNR',6,''
exec FMK.spAddLookup 'PaperSize',7,'A5','A5','A5',N'A5','GNR',7,''
exec FMK.spAddLookup 'PaperSize',8,'B4(JIS)','B4(JIS)','B4(JIS)',N'B4(JIS)','GNR',8,''
exec FMK.spAddLookup 'PaperSize',9,'B5(JIS)','B5(JIS)','B5(JIS)',N'B5(JIS)','GNR',9,''
exec FMK.spAddLookup 'PaperSize',10,'japanese Postcard','japanese Postcard','japanese Postcard',N'japanese Postcard','GNR',10,''
exec FMK.spAddLookup 'PrintOn',0,'چاپ نشود','None',N'چاپ نەكرێت',N'سيتم طباعتها','GNR',0,''
exec FMK.spAddLookup 'PrintOn',1,'چاپ در اولين صفحه','FirstPage',N'چاپ لە يەكەمين لاپەڕەدا',N'طباعة الصفحة الأولى','GNR',1,''
exec FMK.spAddLookup 'PrintOn',2,'چاپ در آخرين صفحه','LastPage',N'چاپ لە دوايين لاپەڕەدا',N'طباعة الصفحة الأخيرة','GNR',2,''
exec FMK.spAddLookup 'PrintOn',3,'چاپ در صفحات فرد','OddPages',N'چاپ لە لاپەڕە تاقەكاندا',N'طباعة صفحات فردية','GNR',3,''
exec FMK.spAddLookup 'PrintOn',4,'چاپ در صفحات زوج','EvenPages',N'چاپ لە لاپەڕە جووتەكاندا',N'طباعة الصفحات الزوجية','GNR',4,''
exec FMK.spAddLookup 'PrintOn',5,'چاپ در باندهاي تكرار','RepeatedBand',N'چاپ لە باندە دووپاتەكاندا',N' الطباعة في النطاقات المترددة','GNR',5,''
exec FMK.spAddLookup 'RgDataSourceType',0,'لطفا ورودي را مشخص كنيد','None',N'تكايە هاتنگەكە دياري بكەن.',N'يرجى تحديد','GNR',0,''
exec FMK.spAddLookup 'RgDataSourceType',1,'موجوديت','DataSet',N'بوونەتي',N'ممتلكات','GNR',1,''
exec FMK.spAddLookup 'RgDataSourceType',2,'اسكريپت','Query',N'ئێسكريپت',N'السيناريو','GNR',2,''
exec FMK.spAddLookup 'RgDataSourceType',3,'جدول','Table',N'شانە',N'جدول','GNR',3,''

exec FMK.spAddLookup 'ShiftMode',0,'هرگز','Never',N'هەرگيز',N'أبدا','GNR',0,''
exec FMK.spAddLookup 'ShiftMode',1,'هميشه','Always',N'هەميشە',N'دائما','GNR',1,''
exec FMK.spAddLookup 'ShiftMode',2,'همپوشاني','WhenOverlapped',N'يەك داپۆشين',N'تداخل','GNR',2,''

exec FMK.spAddLookup 'SortOrder',0,'هيچكدام','None',N'هيچ‌يەك',N'لا شيء','GNR',0,''
exec FMK.spAddLookup 'SortOrder',1,'صعودي','Ascending',N'چوونەسەر',N'تصاعدي','GNR',1,''
exec FMK.spAddLookup 'SortOrder',2,'نزولي','Descending',N'دابەزين',N'التنازلي','GNR',2,''

exec FMK.spAddLookup 'SqlDbType',1,'باينري','Binary',N'باينێري',N'ثنائي','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',2,'منطقي','Bit',N'گونجاو',N'معقول','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',3,'كاراكتر','Char',N'كاراكتێر',N'الحرف','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',4,'تاريخ زمان','DateTime',N'رێكەوت كات',N'تاريخ الزمن','GNR',2,''
exec FMK.spAddLookup 'SqlDbType',5,'اعشاري متوسط','Decimal',N'دەيانەي ناوەندي',N' العشري المتوسط','GNR',5,''
exec FMK.spAddLookup 'SqlDbType',6,'اعشاري بزرگ','Float',N'دەيانەي گەورە',N'العشري الكبير','GNR',6,''
exec FMK.spAddLookup 'SqlDbType',7,'عكس','Image',N'وێنە',N'الصورة','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',8,'عددي','Int',N'ژمارەيي',N'الرقمية',N'GNR',1,''
exec FMK.spAddLookup 'SqlDbType',9,'پول','Money',N'پارە',N'نقود',N'GNR',7,''
exec FMK.spAddLookup 'SqlDbType',10,'كاراكتر يونيكد','NChar',N'كاراكتێري يونيكۆد',N'حرف  يونيكود','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',11,'متن يونيكد','NText',N'دەقي يونيكۆد',N'نص  يونيكود','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',12,'رشته يونيكد','NVarChar',N'بەشي يونيكۆد',N'سلسلة يونيكود','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',13,'اعشاري كوچك','Real',N'دەيانەي بچووك',N'العشرية الصغيرة','GNR',4,''
exec FMK.spAddLookup 'SqlDbType',15,'تاريخ كوچك','SmallDateTime',N'رێكەوتي بچووك',N'تاريخ صغير','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',16,'عدد كوچك','SmallInt',N'ژمارەي بچووك',N'عدد قليل','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',18,'متن غير يونيكد','Text',N'دەقي جگە يونيكۆد',N'نص غير يونيكود ','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',20,'عدد خيلي كوچك','TinyInt',N'ژمارەي زۆر بچووك',N'عدد قليل جدا','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',21,'باينري بزرگ','VarBinary',N'باينێري گەورە',N'ثنائي كبير','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',22,'رشته','VarChar',N'بەش',N'سلسلة','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',25,'Xml','Xml','Xml',N'Xml','GNR',7,''
exec FMK.spAddLookup 'SqlDbType',31,'تاريخ','Date',N'رێكەوت',N'التاريخ','GNR',3,''

exec FMK.spAddLookup 'StringTrimming',0,'None','None','None',N'None','GNR',0,''
exec FMK.spAddLookup 'StringTrimming',1,'Character','Character','Character',N'Character','GNR',1,''
exec FMK.spAddLookup 'StringTrimming',2,'Word','Word','Word',N'Word','GNR',2,''
exec FMK.spAddLookup 'StringTrimming',3,'EllipsisCharacter','EllipsisCharacter','EllipsisCharacter',N'EllipsisCharacter','GNR',3,''
exec FMK.spAddLookup 'StringTrimming',4,'EllipsisWord','EllipsisWord','EllipsisWord',N'EllipsisWord','GNR',4,''
exec FMK.spAddLookup 'StringTrimming',5,'EllipsisPath','EllipsisPath','EllipsisPath',N'EllipsisPath','GNR',5,''

exec FMK.spAddLookup 'TotalType',0,'جمع','Sum',N'كۆ',N'المجموع ','GNR',0,''
exec FMK.spAddLookup 'TotalType',1,'كمينه','Min',N'كەمينە',N'الحد الأدنى','GNR',1,''
exec FMK.spAddLookup 'TotalType',2,'بيشينه','Max',N'زۆرينە',N'الحد الأقصي','GNR',2,''
exec FMK.spAddLookup 'TotalType',3,'ميانگين','Avg',N'مامناوەند',N'المعدل','GNR',3,''
exec FMK.spAddLookup 'TotalType',4,'تعداد','Count',N'رادە',N'عدد','GNR',4,''

exec FMK.spAddLookup 'RgBorderSize',0,'#','Custom','#',N'#','GNR',0,''
exec FMK.spAddLookup 'RgBorderSize',25,'¼','Quarter',N'¼',N'¼','GNR',1,''
exec FMK.spAddLookup 'RgBorderSize',50,'½','Half',N'½',N'1','GNR',2,''
exec FMK.spAddLookup 'RgBorderSize',100,'1','One','1',N'1','GNR',3,''
exec FMK.spAddLookup 'RgBorderSize',150,'1½','OneAndHalf',N'1½',N'1½','GNR',4,''
exec FMK.spAddLookup 'RgBorderSize',200,'2','Tow','2',N'2','GNR',5,''
exec FMK.spAddLookup 'RgBorderSize',300,'3','Tree','3',N'4','GNR',6,''
exec FMK.spAddLookup 'RgBorderSize',400,'4','Four','4',N'4','GNR',7,''
exec FMK.spAddLookup 'RgBorderSize',500,'5','Five','5',N'5','GNR',8,''
exec FMK.spAddLookup 'RgBorderSize',600,'6','Six','6',N'6','GNR',9,''

exec FMK.spAddLookup 'ReportMetaDataType',0,'عادي','Normal',N'',N'','FMK',0,''
exec FMK.spAddLookup 'ReportMetaDataType',1,'بر اساس مشتري','CustomerCodeBased',N'',N'','FMK',1,''
