exec FMK.spAddLookup 'EntityIsActive',0,'غير فعال','InActive',N'ناچالاك',N'غير النشيط','RPA',2,''
exec FMK.spAddLookup 'EntityIsActive',1,'فعال','Active',N'چالاك',N'الناشط','RPA',1,''

exec FMK.spAddLookup 'BankAccountType',0,'','None','','','RPA',0,''
exec FMK.spAddLookup 'BankAccountType',1,'ساير','Other',N'ديكە',N'الآخر','RPA',1,''
exec FMK.spAddLookup 'BankAccountType',2,'جاري','Jari',N'لەگەڕ',N'التيار/الجاري','RPA',2,''
exec FMK.spAddLookup 'BankAccountType',3,'سيبا','Siba',N'سيبا',N'سيبا','RPA',3,''
exec FMK.spAddLookup 'BankAccountType',4,'مهر','Mehr',N'رەزبەر',N'تشرين الاول','RPA',4,''
exec FMK.spAddLookup 'BankAccountType',5,'سپهر','Sepehr',N'سپێهر',N'حساب السبهر','RPA',5,''
exec FMK.spAddLookup 'BankAccountType',6,'جاري طلايي','Jari Talaee',N'لەگەڕي زێڕين',N'حساب الجاري الذهبي','RPA',6,''
exec FMK.spAddLookup 'BankAccountType',7,'جام','Jam',N'جام',N'حساب الجام','RPA',7,''
exec FMK.spAddLookup 'BankAccountType',8,'قرض الحسنه','Gharzolhasaneh',N'قەرزولحەسەنە',N'حساب الوديعة','RPA',8,''
exec FMK.spAddLookup 'BankAccountType',9,'سپرده سرمايه گذاري كوتاه مدت','Sepordeh Kootah Moddat',N'سپێردەي سەرمايەداناني كورت خايەن',N'الوديعة الاستثمارية قصيرة الأجل','RPA',9,''
exec FMK.spAddLookup 'BankAccountType',10,'سپرده سرمايه گذاري بلند مدت','Sepordeh Boland Moddat',N'سپێردەي سەرمايەداناني درێژ خايەن',N'الوديعة الاستثمارية  طويلة الأجل','RPA',10,''
exec FMK.spAddLookup 'BankAccountType',11,'عابر بانك','Aber Bank',N'كارت‌ناس',N'جهاز الصراف الآلي','RPA',11,''
