exec FMK.spAddLookup 'HeaderState',1,'ثبت شده','Saved',N'تۆماركراو',N'مسجل','RPA',1,''
exec FMK.spAddLookup 'HeaderState',2,'سند حسابداري صادر شده','Vouchered',N'بەڵگەي ژمێرياري دەركراو',N'أصدرت وثيقة المحاسبية','RPA',2,''
exec FMK.spAddLookup 'HeaderState',4,'استقرار','Initial','',N'الإنشاء','RPA',3,''

exec FMK.spAddLookup 'RpaDocType',1,'موجودي اوليه','Opening Balance',N'هەبووي سەرەتايي',N'الاوراق المالية الأولي','Rpa',1,''
exec FMK.spAddLookup 'RpaDocType',2,'موجودي اوليه','Opening Balance',N'هەبووي سەرەتايي',N'الاوراق المالية الأولي','Rpa',2,''
exec FMK.spAddLookup 'RpaDocType',3,'موجودي اوليه','Opening Balance',N'هەبووي سەرەتايي',N'الاوراق المالية الأولي','Rpa',3,''
exec FMK.spAddLookup 'RpaDocType',10,'رسيد دريافت','Receipt Note',N'بەڵگەنامەي وەرگرتن',N'ايصال التسديد','Rpa',10,''
exec FMK.spAddLookup 'RpaDocType',11,'دريافت چك','Cheque Receipt',N'وەرگرتني چەك',N'استلام الشيكات','Rpa',11,''
exec FMK.spAddLookup 'RpaDocType',12,'حواله','Draft',N'حەواڵە',N'مسودة','Rpa',12,''
exec FMK.spAddLookup 'RpaDocType',13,'دريافت از كارت خوان','Card Reader Receipt',N'وەرگرتن لە كارت‌ناس',N'تحميل قارئ البطاقة','Rpa',13,''
exec FMK.spAddLookup 'RpaDocType',14,'دريافت چك واخواستي','Protested Cheque Receipt',N'وەرگرتني چەكي پێشبڕيدار',N'تلقي  الشيك الاحتجاجي','Rpa',14,''
exec FMK.spAddLookup 'RpaDocType',15,'شارژ تنخواه','Petty cash Charge',N'',N'','Rpa',15,''
exec FMK.spAddLookup 'RpaDocType',20,'اعلاميه پرداخت','Payment Statement',N'رەسيدي پێدان',N'اعلان التسديد','Rpa',20,''
exec FMK.spAddLookup 'RpaDocType',21,'پرداخت چك','Cheque Payment',N'پێداني چەك',N'دفع الشيك','Rpa',21,''
exec FMK.spAddLookup 'RpaDocType',22,'اعلاميه برداشت','Withdrawal',N'راگەيەندراوي هەڵگرتن',N'إعلان الانسحاب','Rpa',22,''
exec FMK.spAddLookup 'RpaDocType',23,'خرج كردن چك','Spending Cheque',N'خەرج كردني چەك',N'تحقق الشيك','Rpa',23,''
exec FMK.spAddLookup 'RpaDocType',24,'ابطال چك','Void Cheque',N'هەڵوەشاندنەوەي چەك',N' إلغاء الشيك','Rpa',24,''
exec FMK.spAddLookup 'RpaDocType',30,'عمليات بانكي چك','Note Receivable Banking Procedures',N'كردە بانكيەكاني چەك',N'العمليات المصرفية للشيك','Rpa',30,''
exec FMK.spAddLookup 'RpaDocType',31,'واگذار به بانك','Transfer Cheque To Bank',N'رادەست‌كار بە بانك',N'تعيين للبنك','Rpa',31,''
exec FMK.spAddLookup 'RpaDocType',32,'وصول چك','Cashing Cheque',N'نەختەوە كردني چەك',N'الحصول علي شيك','Rpa',32,''
exec FMK.spAddLookup 'RpaDocType',33,'واخواست چك','Returned Cheque',N'پێشبڕي چەك',N'احتجاج الشيك','Rpa',33,''
exec FMK.spAddLookup 'RpaDocType',34,'نقد كردن چك','Cheque Cash',N'نەختەوەكردني چەك',N'تحقق صرف الشيك','Rpa',34,''
exec FMK.spAddLookup 'RpaDocType',41,'وصول چك پرداختني','Payment Cheque Cashing',N'نەختەوە كردني چەكي پێدراو',N'توصيل مجموعة من الشيكات المستحقة التسديدية','Rpa',41,''
exec FMK.spAddLookup 'RpaDocType',50,'استرداد چك','Refund Cheque','',N'ارتداد الشيك','Rpa',50,''
exec FMK.spAddLookup 'RpaDocType',51,'استرداد چك دريافتني','Refund Receipt Cheque',N'گەرانەوەي چەكي وەرگيراو ',N'استرداد الشيكات المستحقة للاستلام','Rpa',51,''
exec FMK.spAddLookup 'RpaDocType',52,'استرداد چك پرداختني','Refund Payment Cheque',N'گەرانەوي چەكي پێدراو',N'اعادة شيكات المبالغ الفائضة المستحقة','Rpa',52,''
exec FMK.spAddLookup 'RpaDocType',61,'تسويه كارت خوان','Card Reader Polling',N'ساوكردني كارت‌ناس',N'بطاقة تسوية قارئ','RPA',20,''
exec FMK.spAddLookup 'RpaDocType',53,'برگشت چك خرج شده','Return Spended Cheque',N'هەڵگەڕانەوەي چەكي خەرج كراو',N'اعادة الشيك المستفاد','Rpa',51,''
exec FMK.spAddLookup 'RpaDocType',54,'برگشت چك خرج شده واخواستي','Return Spended Returned Cheque',N'هەڵگەڕاوەي چەكي خەرج كراوي پێشبڕيدار',N'استرداد الشيك المستاد المطلوبة','Rpa',52,''
exec FMK.spAddLookup 'RpaDocType',60,'سپرده نقدي ضمانت نامه','Cash Deposit For Guarantee',N'',N'','Rpa',60,''
exec FMK.spAddLookup 'RpaDocType',62,'كارمزد بانكي','Bank FEE',N'',N'','Rpa',62,''
exec FMK.spAddLookup 'RpaDocType',70,'موجودي اوليه','Opening Balance',N'هەبووي سەرەتايي',N'الاوراق المالية الأولي','Rpa',70,''
