exec FMK.spAddLookup 'OrderStatus',1,'فعال','ACTIVE',N'چالاك',N'الناشط','SLS',1,''
exec FMK.spAddLookup 'OrderStatus',2,'غير فعال','INACTIVE',N'ناچالاك',N'غير النشيط','SLS',2,''
exec FMK.spAddLookup 'ProductType',1,'كالا','Part',N'كەرەستە',N'البضائع','SLS',1,''
exec FMK.spAddLookup 'ProductType',2,'خدمت','Service',N'خزمەت',N'خدمة','SLS',2,''
exec FMK.spAddLookup 'ProductType',3,'','','','','SLS',3,''
exec FMK.spAddLookup 'ItemPriceSummaryType',1,'آخرين قيمت فروش'         ,'Last sale price',N'كۆتايي نرخي فرۆشتن',N'سعر البيع الأخير','SLS',1,''
exec FMK.spAddLookup 'ItemPriceSummaryType',2,'آخرين قيمت فروش به مشتري','Last sale price to customer',N'كۆتايي نرخي فرۆشتن بۆ كڕيار',N'سعر البيع الأخير للزبائن','SLS',2,''
exec FMK.spAddLookup 'ItemPriceSummaryType',3,'آخرين قيمت خريد'         ,'Last bu price',N'كۆتايي نرخي كڕين',N'سعر الشراء الأخير','SLS',3,''
exec FMK.spAddLookup 'CommissionInvoiceType',1,'فاكتور فروش'  ,'Invoice','پسولەي فرۆش',N'فاتورة المبيعات','SLS',1,''
exec FMK.spAddLookup 'CommissionInvoiceType',2,'فاكتور برگشتي','ReturnedInvoice','گەرانەوەي پسولە',N'فاتورة العودة','SLS',2,''
