exec FMK.spAddKeyword 'Sales.InvoiceManagement.DsCommission.List', N'فهرست پورسانت، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.DsCommission.New', N'حق العمل، كميسيون، درصد سهم، بازارياب، فروشنده', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.DsCommissionCalculation.List', N'حق العمل محاسبه شده، كمسيون محاسبه شده، سهم محاسبه شده بازارياب', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.DsCommissionCalculation.New', N'سهم بازارياب، كميسيون، حق العمل', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.DsInvoice.List', N'فهرست فاكتور فروش، ليست ', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.DsInvoice.New', N'برگ، صورتحساب، سياهه، كالا، ابطال', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.DsQuotation.List', N'فهرست پيش فاكتورها، پرفورما، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.DsQuotation.New', N'استعلام قيمت، پرفورما', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.DsReturnedInvoice.List', N'فهرست برگشت از فروش، سياهه، كالاها، ليست', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.DsReturnedInvoice.New', N'برگشت از فروش، سياهه', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.DummyEntity.CommissionReview', N'ريز حساب، فاكتورها، مشتريان، گزارش حساب، كميسيون، حق العمل، واسط', N'', N'', N''
exec FMK.spAddKeyword 'Sales.InvoiceManagement.Review', N'گزارش، كالاهاي پرفروش، كالاهاي فروش رفته، سود، اقلام، اسناد، بهاي تمام شده', N'', N'', N''
