exec FMK.spAddLookup 'SectionResponsible',0,' ',' ','',N'','SLS',0,''
exec FMK.spAddLookup 'SectionResponsible',1,'الف','A',N'ئەلف',N'أ','SLS',1,''
exec FMK.spAddLookup 'SectionResponsible',2,'ب','B',N'ب',N'ب','SLS',2,''

exec FMK.spAddLookup 'EconomicCodeState',0,'نام كاربري دارم','I have User Name',N'ناوي به‌كارهێنه‌ر هەيە',N'اسم المستخدم لي','SLS',0,''
exec FMK.spAddLookup 'EconomicCodeState',1,'كد رهگيري دارم','I have Tracking Code',N'كۆدي شوێن‌گيريم هەيە',N'أنا شفرة التتبع لي','SLS',1,''
exec FMK.spAddLookup 'EconomicCodeState',2,'پيش ثبت نام كد اقتصادي نكرده ام','I have not Register for Economic Code',N'پێش ناونووسي كۆدي ئابووريم نەكردووە',N'لم أسجل كود الاقتصادي لنفسي','SLS',2,''


exec FMK.spAddLookup 'TaxOffice',12,'مازندران','Mazandaran',N'مازندەران',N'مازندران','SLS',12,''
exec FMK.spAddLookup 'TaxOffice',13,'آذربايجان شرقي','Azarbaijan_Sharghi',N'ئازربايجاني رۆژهەڵات',N'الشرق اذربيجان','SLS',13,''
exec FMK.spAddLookup 'TaxOffice',14,'آذربايجان غربي','Azarbaijan_Gharbi',N'ئازربايجاني رۆژئاوا',N'اذربيجان الغربية','SLS',14,''
exec FMK.spAddLookup 'TaxOffice',15,'كرمانشاه','Kermanshah',N'كرماشان',N'كرمنشاه','SLS',15,''
exec FMK.spAddLookup 'TaxOffice',16,'خوزستان','Khozestan',N'خووزستان',N'خوزستان','SLS',16,''
exec FMK.spAddLookup 'TaxOffice',17,'فارس','Fars',N'فارس',N'فارس','SLS',17,''
exec FMK.spAddLookup 'TaxOffice',18,'كرمان','Kerman',N'كرمان',N'كرمان','SLS',18,''
exec FMK.spAddLookup 'TaxOffice',19,'خراسان رضوي','Khorasan_Razavi',N'خۆراساني رەزەوي',N'خراسان رضوي','SLS',19,''
exec FMK.spAddLookup 'TaxOffice',20,'اصفهان','Esfahan',N'ئيسفەهان',N'أصفهان','SLS',20,''
exec FMK.spAddLookup 'TaxOffice',21,'خراسان شمالي','Khorasan_Shomali',N'خۆراساني باكوور',N'شمال خراسان','SLS',21,''
exec FMK.spAddLookup 'TaxOffice',22,'كردستان','Kordestan',N'كوردستان',N'كردستان','SLS',22,''
exec FMK.spAddLookup 'TaxOffice',23,'هرمزگان','Hormozgan',N'هورمزگان',N'هرمزكان','SLS',23,''
exec FMK.spAddLookup 'TaxOffice',24,'همدان','Hamedan',N'هەمەدان',N'همدان','SLS',24,''
exec FMK.spAddLookup 'TaxOffice',25,'چهار محال بختياري','Chahar_Mahal_Bakhtiari',N'چوارمەحاڵي بەختياري',N'جهار محال بختياري','SLS',25,''
exec FMK.spAddLookup 'TaxOffice',26,'لرستان','Lorestan',N'لۆڕستان',N'ورستان','SLS',26,''
exec FMK.spAddLookup 'TaxOffice',27,'ايلام','Ilam',N'ئيلام',N'إيلام','SLS',27,''
exec FMK.spAddLookup 'TaxOffice',28,'كهگيلويه و بوير احمد','Kohkiloyeh_BoyerAhmad',N'كۆهكيلوويە و بوێرئەحمەد',N'كهكيلويه و بوير احمد','SLS',28,''
exec FMK.spAddLookup 'TaxOffice',29,'زنجان','Zanjan',N'زەنجان',N'زنجان','SLS',29,''
exec FMK.spAddLookup 'TaxOffice',31,'خراسان جنوبي','Khorasan_Jonobi',N'خۆراساني باشوور',N' خراسان جنوبي','SLS',31,''
exec FMK.spAddLookup 'TaxOffice',32,'شهر تهران - جنوب','Tehran_Jonob',N'شاري تاران_باشوور',N'مدينة طهران - جنوب','SLS',10,''
exec FMK.spAddLookup 'TaxOffice',34,'شهر تهران - غرب','Tehran_Gharb',N'شاري تاران_رۆژئاوا',N'مدينة طهران - الغربية','SLS',10,''
exec FMK.spAddLookup 'TaxOffice',35,'شهر تهران - شرق','Tehran_Shargh',N'شاري تاران_رۆژهەڵات',N'مدينة طهران - الشرق','SLS',10,''
exec FMK.spAddLookup 'TaxOffice',36,'شهر تهران - مركز','Tehran_Markaz',N'شاري تاران_ناوەند',N'مدينة طهران - مركز','SLS',10,''
exec FMK.spAddLookup 'TaxOffice',39,'شهر تهران - موديان بزرگ','Tehran_Bozorg',N'شاري تاران_پيتاكدەراني گەورە',N'مدينة طهران - موديان الكبير','SLS',10,''
exec FMK.spAddLookup 'TaxOffice',40,'شهر تهران - شمال','Tehran_Shomal',N'شاري تاران_باكوور',N'مدينة طهران - شمال','SLS',10,''
exec FMK.spAddLookup 'TaxOffice',44,'مركزي','Markazi',N'ناوەنديي',N'مركزي','SLS',44,''
exec FMK.spAddLookup 'TaxOffice',46,'استان تهران - شهر ري / جنوب','Tehran_Rey',N'پارێزگاي تاران_ شاري رەي/ باشوور',N'محافظة طهران  - مدينة ري / جنوب','SLS',10,''
exec FMK.spAddLookup 'TaxOffice',49,N'البرز - كرج',N'Alborz',N'',N'','SLS',49,''
exec FMK.spAddLookup 'TaxOffice',51,'استان تهران - شميرانات / شمال','Tehran_Shemiran',N'پارێزگاي تاران_ شەميرانات/ باكوور',N'محافظة طهران - شميرانات / شمال','SLS',10,''
exec FMK.spAddLookup 'TaxOffice',52,'استان تهران - شهريار / غرب','Tehran_Shariar',N'پارێزگاي تاران_شەهريار/ رۆژئاوا',N'محافظة طهران - شهريار / الغربية','SLS',10,''
exec FMK.spAddLookup 'TaxOffice',53,'استان تهران - بومهن / شرق','Tehran_Bomhen',N'پارێزگاي تاران_بوومێهێن/ رۆژهەڵات',N'محافظة طهران - بومهن/ الشرق','SLS',10,''
exec FMK.spAddLookup 'TaxOffice',55,'گيلان','Gilan',N'گيلان',N'جيلان','SLS',55,''
exec FMK.spAddLookup 'TaxOffice',61,'اردبيل','Ardebil',N'ئەردەبێڵ',N'أردبيل','SLS',61,''
exec FMK.spAddLookup 'TaxOffice',62,'قم','Ghom',N'قۆم',N'قم','SLS',62,''
exec FMK.spAddLookup 'TaxOffice',63,'قزوين','Ghazvin',N'قەزوين',N'قزوين','SLS',63,''
exec FMK.spAddLookup 'TaxOffice',64,'گلستان','Golestan',N'گوڵستان',N'كلستان','SLS',64,''
exec FMK.spAddLookup 'TaxOffice',66,'سيستان و بلوچستان','Sistan_Balochetan',N'سيستان و بەلووچستان',N'سيستان وبلوشستان','SLS',66,''
exec FMK.spAddLookup 'TaxOffice',77,'يزد','Yazd',N'يەزد',N'يزد','SLS',77,''
exec FMK.spAddLookup 'TaxOffice',88,'بوشهر','Booshehr',N'بووشێهر',N'بوشهر','SLS',88,''
exec FMK.spAddLookup 'TaxOffice',99,'سمنان','Semnan',N'سمنان',N'سمنان','SLS',99,''
		
