exec FMK.spAddLookup 'ApplicationTheme',0,'مشكي','Black',N'رەش',N'أسود','FMK',1,''
exec FMK.spAddLookup 'ApplicationTheme',1,'آبي','Blue',N'شين',N'أزرق','FMK',2,''
exec FMK.spAddLookup 'ApplicationTheme',2,'نقره اي','Silver',N'زيوين',N'فضة','FMK',3,''
exec FMK.spAddLookup 'ApplicationTheme',3,'شيشه اي','VistaGlass',N'شووشەيي',N'زجاجي','FMK',4,''

exec FMK.spAddLookup 'ExtraInformationColumnType',1,'رشته','String',N'بەش',N'سلسلة','FMK',1,''
exec FMK.spAddLookup 'ExtraInformationColumnType',2,'عدد صحيح','Integer',N'ژمارەي تەواو',N'عدد صحيح','FMK',2,''
exec FMK.spAddLookup 'ExtraInformationColumnType',3,'عدد اعشاري','Decimal',N'ژمارەي دەيانە',N'عدد الفاصلة العشرية','FMK',3,''
exec FMK.spAddLookup 'ExtraInformationColumnType',4,'تاريخ','Date',N'رێكەوت',N'التاريخ','FMK',4,''
exec FMK.spAddLookup 'ExtraInformationColumnType',5,'لينك','Url',N'لينك',N'حلقة الوصل','FMK',5,''

exec FMK.spAddLookup 'FiscalYearStatus',1,'فعال','Active',N'چالاك',N'الناشط','FMK',1,''
exec FMK.spAddLookup 'FiscalYearStatus',2,'بسته شده','Closed',N'داخراو',N'مغلق','FMK',2,''

exec FMK.spAddLookup 'SgCulture',1,'فارسي','Persian',N'فارسي',N'اللغة الفارسية','FMK',1,''
exec FMK.spAddLookup 'SgCulture',2,'انگليسي','English',N'ئينگليزي',N'الإنجليزية','FMK',2,''
exec FMK.spAddLookup 'SgCulture',3,'كردي','Kurdish',N'كۆردي',N'كردي','FMK',3,''
exec FMK.spAddLookup 'SgCulture',4,'عربي','Arabic',N'عربي',N'العربية','FMK',4,''

exec FMK.spAddLookup 'MajorCalendar',1,'هجري شمسي','Persian',N'كۆچي هەتاوي',N'هجرية شمسية','FMK',1,''
exec FMK.spAddLookup 'MajorCalendar',2,'ميلادي','Christian',N'زاييني',N'الميلادي','FMK',2,''

exec FMK.spAddLookup 'LogicalOperator',1,'برابر با','equals',N'يەكسانە لەگەڵ',N'يساوي','FMK',1,''
exec FMK.spAddLookup 'LogicalOperator',2,'بزرگتر از','greater than',N'گەورەتر لە',N'أكبر من','FMK',2,''
exec FMK.spAddLookup 'LogicalOperator',3,'بزرگتر يا مساوي با','greater than or equal',N'گەورەتر يان بەرانبەرە لەگەڵ',N'أكبر من أو يساوي','FMK',3,''
exec FMK.spAddLookup 'LogicalOperator',4,'كوچكتر از','less than',N'بچووكترە لە',N'أقل من','FMK',4,''
exec FMK.spAddLookup 'LogicalOperator',5,'كوچكتر يا مساوي با','less than or equal',N'بچووكتر يان بەرانبەرە لەگەڵ',N'أقل من أو يساوي','FMK',5,''
exec FMK.spAddLookup 'LogicalOperator',6,'مخالف با','not equals',N'دژە لەگەڵ',N'خلافا ل','FMK',6,''

exec FMK.spAddLookup 'NumberingMethod',1,'خودكار','Automatic',N'ئوتۆماتيك',N'تلقائيا','FMK',1,''
exec FMK.spAddLookup 'NumberingMethod',2,'دستي','Manual',N'دەستيي',N'كتيب يدوي','FMK',2,''

exec FMK.spAddLookup 'Months',0,'','',N'','','FMK',0,''
exec FMK.spAddLookup 'Months',1,'فروردين','January',N'خاكەلێوە',N'نيسان','FMK',1,''
exec FMK.spAddLookup 'Months',2,'ارديبهشت','February',N'گوڵان',N'مايو','FMK',2,''
exec FMK.spAddLookup 'Months',3,'خرداد','March',N'جۆزەردان',N'حزيران','FMK',3,''
exec FMK.spAddLookup 'Months',4,'تير','April',N'پووشپەڕ',N'تموز','FMK',4,''
exec FMK.spAddLookup 'Months',5,'مرداد','May',N'گەلاوێژ',N'آب','FMK',5,''
exec FMK.spAddLookup 'Months',6,'شهريور','June',N'خەرمانان',N'أيلول','FMK',6,''
exec FMK.spAddLookup 'Months',7,'مهر','July',N'رەزبەر',N'تشرين الاول','FMK',7,''
exec FMK.spAddLookup 'Months',8,'آبان','August',N'گەڵاڕێزان',N'تشرين الثاني','FMK',8,''
exec FMK.spAddLookup 'Months',9,'آذر','September',N'سەرماوەز',N'كانون الاول','FMK',9,''
exec FMK.spAddLookup 'Months',10,'دي','October',N'بەفرانبار',N'شهر أكتوبر 10','FMK',10,''
exec FMK.spAddLookup 'Months',11,'بهمن','November',N'رێبەندان',N'شهر نوفمبر 11','FMK',11,''
exec FMK.spAddLookup 'Months',12,'اسفند','December',N'رەشەمە',N'مارس','FMK',12,''

Delete From Fmk.[Lookup] where [Type] = 'SubSystemsKind'
exec FMK.spAddLookup 'SubSystemsKind',0,'مشتريان و فروش','Customers & Sales',N'كڕياران و فرۆش',N'الزبائن و المبيعات','FMK',0,''
exec FMK.spAddLookup 'SubSystemsKind',1,'تامين كنندگان و انبار','Vendors & Inventory',N'دابينكاران و كۆگا',N'الموردين و المستودعات','FMK',4,''
exec FMK.spAddLookup 'SubSystemsKind',2,'دريافت و پرداخت','Receipt & Payment',N'وەرگرتن و پێدان',N'التلقي و الدفع','FMK',6,''
exec FMK.spAddLookup 'SubSystemsKind',3,'حسابداري','Accounting',N'ژمێرياري',N'المحاسبة','FMK',8,''
exec FMK.spAddLookup 'SubSystemsKind',4,'حقوق و دستمزد','Payroll',N'مووچە و حەقدەست',N'الرواتب و الاجور','FMK',9,''
exec FMK.spAddLookup 'SubSystemsKind',7,'خرده فروشي','Point of sale',N'وردەفرۆشي',N'البيع بالتجزئة','FMK',1,''
exec FMK.spAddLookup 'SubSystemsKind',8,'پيمانكاري','Contract',N'بەڵێندارێتيي',N'تعاقد','FMK',10,''
exec FMK.spAddLookup 'SubSystemsKind',9,'سفارش كار','Work Order',N'داواكاري',N'ترتيب العمل','FMK',5,''
exec FMK.spAddLookup 'SubSystemsKind',10,'دارايي ثابت','Fixed Asset Management',N'',N'','FMK',7,''
exec FMK.spAddLookup 'SubSystemsKind',11,'ارتباطات','Communication',N'',N'','GNR',13,''
exec FMK.spAddLookup 'SubSystemsKind',12,'سفارش‌گيري و پخش','Distribution','','','FMK',2,''
exec FMK.spAddLookup 'SubSystemsKind',13,'سفارشات و خريد خارجي','Purchase orders Management',N'',N'طلبات الشراء','FMK',3,''
exec FMK.spAddLookup 'SubSystemsKind',14,'تداركات و خريد داخلي','Internal Logistic',N'',N'','FMK',3,''
exec FMK.spAddLookup 'SubSystemsKind',15,'تداركات و خريد','Logistic',N'',N'','FMK',3,''
exec FMK.spAddLookup 'SubSystemsKind',16,'گزارش‌هاي مديريتي','CompanyDashboard',N'',N'','GNR',12,''
exec FMK.spAddLookup 'SubSystemsKind',17,'سامانه موديان مالياتي','TaxPayer',N'',N'','GNR',11,''


exec FMK.spAddLookup 'SubSystemsKind',5,'شركت','Company',N'كۆمپانيا',N'الشركة','FMK',14,''
exec FMK.spAddLookup 'SubSystemsKind',6,'تنظيمات','Configurations',N'رێكخستنەكان',N'الإعدادات','FMK',15,''


exec FMK.spAddLookup 'InputType',0,'موجوديت','Entity',N'بوونەتي',N'ممتلكات','FMK',0,''
exec FMK.spAddLookup 'InputType',1,'پرس و جو','Script',N'تاوتوێ',N'تحقيق','FMK',1,''

exec FMK.spAddLookup 'IOType',0,'اكسل','Entity',N'ئەكسێل',N'إكسيل','FMK',0,''
exec FMK.spAddLookup 'IOType',1,'متن','Text',N'دەق',N'النص','FMK',1,''
exec FMK.spAddLookup 'IOType',2,'DBF','DBF','DBF',N'DBF','FMK',2,''

exec FMK.spAddLookup 'ImportFlag',1,' ','','',N'','FMK',1,''
exec FMK.spAddLookup 'ImportFlag',2,'دريافت شد','Imported',N'وەرگيرا',N'تلقى','FMK',2,''
exec FMK.spAddLookup 'ImportFlag',3,'خطا','Error',N'كێشە',N'خطأ','FMK',3,''

exec FMK.spAddLookup 'Seperator',0,'كاما','Camma',N'كاما',N'فاصلة','FMK',0,''
exec FMK.spAddLookup 'Seperator',1,'تب','Tab',N'تێب',N'علامة التبويب','FMK',1,''
exec FMK.spAddLookup 'Seperator',2,'فاصله خالي','Space',N'مەوداي بەتاڵ',N'مسافة فارغة','FMK',2,''
exec FMK.spAddLookup 'Seperator',3,'هيچكدام','None',N'هيچ‌يەك',N'لا شيء','FMK',3,''
exec FMK.spAddLookup 'Seperator',4,'كاما نقطه','Semicolon',N'كاما نوختە',N'فاصلة منقوطة','FMK',4,''

exec FMK.spAddLookup 'Season',0,'','',N'','','FMK',0,''
exec FMK.spAddLookup 'Season',1,'بهار','spring',N'بەهار',N'ربيع','FMK',1,''
exec FMK.spAddLookup 'Season',2,'تابستان','summer',N'هاوين',N'الصيف','FMK',2,''
exec FMK.spAddLookup 'Season',3,'بهار/تابستان','spring/summer',N'بەهار/ هاوين',N'الربيع / الصيف','FMK',2,''
exec FMK.spAddLookup 'Season',4,'پاييز','fall',N'پاييز',N'الخريف','FMK',3,''
exec FMK.spAddLookup 'Season',5,'بهار/پاييز','fall',N'بەهار/ پاييز',N'الربيع / الخريف','FMK',3,''
exec FMK.spAddLookup 'Season',6,'تابستان/پاييز','fall',N'هاوين/ پاييز',N'الصيف / الخريف','FMK',3,''
exec FMK.spAddLookup 'Season',7,'بهار/تابستان/پاييز','fall',N'بەهار/ هاوين/ پاييز',N'الربيع / الصيف / الخريف','FMK',3,''
exec FMK.spAddLookup 'Season',8,'زمستان','winter',N'زستان',N'شتاء','FMK',4,''
exec FMK.spAddLookup 'Season',9,'بهار/زمستان','spring',N'بەهار/ زستان',N'الربيع / شتاء','FMK',1,''
exec FMK.spAddLookup 'Season',10,'تابستان/زمستان','summer',N'هاوين/ زستان',N'صيف / شتاء','FMK',2,''
exec FMK.spAddLookup 'Season',11,'بهار/تابستان/زمستان','spring/summer',N'بەهار/ هاوين/ زستان',N'ربيع / صيف / شتاء','FMK',2,''
exec FMK.spAddLookup 'Season',12,'پاييز/زمستان','fall',N'پاييز/ زستان',N'خريف / شتاء','FMK',3,''
exec FMK.spAddLookup 'Season',13,'بهار/پاييز/زمستان','fall',N'بەهار/ بەهار/ زستان',N'الربيع / الخريف / الشتاء','FMK',3,''
exec FMK.spAddLookup 'Season',14,'تابستان/پاييز/زمستان','fall',N'هاوين/ پاييز/ زستان',N'الصيف / الخريف / الشتاء','FMK',3,''
exec FMK.spAddLookup 'Season',15,'بهار/تابستان/پاييز/زمستان','fall',N'بەهار/ هاوين/ پاييز/ زستان',N'الصيف / الخريف / الشتاء','FMK',3,''
