exec FMK.spAddLookup 'TaxPayerPartyType', 0, N'' , '' , '' , '' , 'GNR', 0,''
exec FMK.spAddLookup 'TaxPayerPartyType', 1, N'حقيقي' , '' , '' , '' , 'GNR', 1,''
exec FMK.spAddLookup 'TaxPayerPartyType', 2, N'حقوقي' , '' , '' , '' , 'GNR', 2,''
exec FMK.spAddLookup 'TaxPayerPartyType', 3, N'مشاركت مدني' , '' , '' , '', 'GNR', 3, ''
exec FMK.spAddLookup 'TaxPayerPartyType', 4, N'اتباع غير ايراني' , '' , '' , '', 'GNR', 4, ''

exec FMK.spAddLookup 'TaxPayerBillSubmitType', 0, N'', '', '', '', 'GNR', 0, ''
exec FMK.spAddLookup 'TaxPayerBillSubmitType', 1, N'ارسال مستقيم اطلاعات به سامانه', '', '', '', 'GNR', 1, ''
exec FMK.spAddLookup 'TaxPayerBillSubmitType', 2, N'ارسال اطلاعات از طريق شركت معتمد سام', '', '', '', 'GNR', 2, ''
exec FMK.spAddLookup 'TaxPayerBillSubmitType', 3, N'ارسال اطلاعات از طريق شركت معتمد كيسان', '', '', '', 'GNR', 3, ''
exec FMK.spAddLookup 'TaxPayerBillSubmitType', 4, N'ارسال اطلاعات از طريق شركت معتمد تيس', '', '', '', 'GNR', 4, ''
exec FMK.spAddLookup 'TaxPayerBillSubmitType', 5, N'ارسال مستقيم اطلاعات به سامانه نسخه 2', '', '', '', 'GNR', 1, ''

exec FMK.spAddLookup 'TaxPayerBillState', 0, N'' , '' , '' , '', 'GNR', 0, ''
exec FMK.spAddLookup 'TaxPayerBillState', 1, N'نياز به ارسال' , '' , '' , '', 'GNR', 1, ''
exec FMK.spAddLookup 'TaxPayerBillState', 2, N'در انتظار استعلام' , '' , '' , '', 'GNR', 2, ''
exec FMK.spAddLookup 'TaxPayerBillState', 3, N'خطا در ارسال' , '' , '' , '', 'GNR', 3, ''
exec FMK.spAddLookup 'TaxPayerBillState', 4, N'ارسال شده' , '' , '' , '', 'GNR', 4, ''

exec FMK.spAddLookup 'TaxPayerBillStateInWorkBook', 0, N'' , '' , '' , '', 'GNR', 0, ''
exec FMK.spAddLookup 'TaxPayerBillStateInWorkBook', 1, N'تاييد' , '' , '' , '', 'GNR', 1, ''
exec FMK.spAddLookup 'TaxPayerBillStateInWorkBook', 2, N'رد' , '' , '' , '', 'GNR', 2, ''
exec FMK.spAddLookup 'TaxPayerBillStateInWorkBook', 3, N'عدم نياز به واكنش' , '' , '' , '', 'GNR', 3, ''
exec FMK.spAddLookup 'TaxPayerBillStateInWorkBook', 4, N'در انتظار واكنش' , '' , '' , '', 'GNR', 4, ''

exec FMK.spAddLookup 'TaxPayerBillActionType', 0, N'' , '' , '' , '', 'GNR', 0, ''
exec FMK.spAddLookup 'TaxPayerBillActionType', 1, N'اصلي' , '' , '' , '', 'GNR', 1, ''
exec FMK.spAddLookup 'TaxPayerBillActionType', 2, N'اصلاحي' , '' , '' , '', 'GNR', 2, ''
exec FMK.spAddLookup 'TaxPayerBillActionType', 3, N'ابطالي' , '' , '' , '', 'GNR', 3, ''
exec FMK.spAddLookup 'TaxPayerBillActionType', 4, N'برگشت از فروش' , '' , '' , '', 'GNR', 4, ''

exec FMK.spAddLookup 'TaxPayerBillBillType', 0, N'' , '' , '' , '', 'GNR', 0, ''
exec FMK.spAddLookup 'TaxPayerBillBillType', 1, N'نوع اول' , '' , '' , '', 'GNR', 1, ''
exec FMK.spAddLookup 'TaxPayerBillBillType', 2, N'نوع دوم' , '' , '' , '', 'GNR', 2, ''

exec FMK.spAddLookup 'TaxPayerBillBillPattern', 0, N'' , '' , '' , '', 'GNR', 0, ''
exec FMK.spAddLookup 'TaxPayerBillBillPattern', 1, N'فروش' , '' , '' , '', 'GNR', 1, ''
exec FMK.spAddLookup 'TaxPayerBillBillPattern', 2, N'فروش ارز' , '' , '' , '', 'GNR', 2, ''
exec FMK.spAddLookup 'TaxPayerBillBillPattern', 4, N'قرارداد پيمانكاري' , '' , '' , '', 'GNR', 4, ''
exec FMK.spAddLookup 'TaxPayerBillBillPattern', 7, N'صادرات' , '' , '' , '', 'GNR', 7, ''

exec FMK.spAddLookup 'TaxPayerBillSettlementType', 0, N'' , '' , '' , '', 'GNR', 0, ''
exec FMK.spAddLookup 'TaxPayerBillSettlementType', 1, N'نقدي' , '' , '' , '', 'GNR', 1, ''
exec FMK.spAddLookup 'TaxPayerBillSettlementType', 2, N'نسيه' , '' , '' , '', 'GNR', 2, ''
exec FMK.spAddLookup 'TaxPayerBillSettlementType', 3, N'نقدي / نسيه' , '' , '' , '', 'GNR', 3, ''

exec FMK.spAddLookup 'BillSubmitLogRequestType', 1, N'ارسال' , '' , '' , '', 'GNR', 1, ''
exec FMK.spAddLookup 'BillSubmitLogRequestType', 2, N'استعلام' , '' , '' , '', 'GNR', 1, ''

exec FMK.spAddLookup 'BillRelatedVoucherType', 0, N'' , '' , '' , '', 'GNR', 0, ''
exec FMK.spAddLookup 'BillRelatedVoucherType', 1, N'فاكتور' , '' , '' , '', 'GNR', 1, ''
exec FMK.spAddLookup 'BillRelatedVoucherType', 2, N'صورت وضعيت' , '' , '' , '', 'GNR', 2, ''
exec FMK.spAddLookup 'BillRelatedVoucherType', 3, N'اظهارنامه گمركي' , '' , '' , '', 'GNR', 3, ''
exec FMK.spAddLookup 'BillRelatedVoucherType', 4, N'فروش دارايي' , '' , '' , '', 'GNR', 4, ''

exec FMK.spAddLookup 'BillMakingMethod', 0, N'' , '' , '' , '', 'GNR', 0, ''
exec FMK.spAddLookup 'BillMakingMethod', 1, N'خودكار' , '' , '' , '', 'GNR', 1, ''
exec FMK.spAddLookup 'BillMakingMethod', 2, N'دستي' , '' , '' , '', 'GNR', 2, ''

exec FMK.spAddLookup 'TaxPayerBillEntityType', 1, N'فاكتور' , '' , '' , '', 'GNR', 1, ''
exec FMK.spAddLookup 'TaxPayerBillEntityType', 2, N'فاكتور برگشتي' , '' , '' , '', 'GNR', 2, ''
exec FMK.spAddLookup 'TaxPayerBillEntityType', 3, N'فاكتور صادرات خدمات' , '' , '' , '', 'GNR', 3, ''
exec FMK.spAddLookup 'TaxPayerBillEntityType', 4, N'صورت وضعيت' , '' , '' , '', 'GNR', 4, ''
exec FMK.spAddLookup 'TaxPayerBillEntityType', 5, N'اظهارنامه گمركي' , '' , '' , '', 'GNR', 5, ''
exec FMK.spAddLookup 'TaxPayerBillEntityType', 6, N'فاكتور فروش دارايي ثابت' , '' , '' , '', 'GNR', 6, ''
