exec FMK.spAddLookup 'VatItemType',1,'1-فاكتور فروش','1.Sales Invoice',N'پسولەي فرۆش_1',N'فاتورة المبيعات','GNR',1,''
exec FMK.spAddLookup 'VatItemType',2,'2-فاكتور برگشتي','2.Sales Returned Invoice',N'گەرانەوەي پسولە2',N'2-الفاتورة الاستردادية','GNR',2,''
exec FMK.spAddLookup 'VatItemType',3,'3-رسيد انبار','3.Inventory Receipt',N'رەسيدي كۆگا_3',N'3-ايصال استلام المستودع ','GNR',3,''
exec FMK.spAddLookup 'VatItemType',4,'4-برگشت رسيد ','4.Inventory Returned Receipt',N'هەڵگەڕاوەي رەسيد_4',N'4- عودة الايصال','GNR',4,''
exec FMK.spAddLookup 'VatItemType',5,'5-فاكتور خريد خدمات ','4.Service Inventory Purchase Invoice',N'پسولەي كڕيني خزمەتگوزارييەكان5',N'5- فاتورة شراء الخدمات','GNR',5,''
exec FMK.spAddLookup 'VatItemType',6,'6-فاكتور خريد دارايي ','6.Asset Purchase Invoice','6.Asset Purchase Invoice','6.Asset Purchase Invoice','GNR',6,''
exec FMK.spAddLookup 'VatItemType',7,'7-فروش دارايي ','7.Asset Sale','7.Asset Sale','7.Asset Sale','GNR',7,''
exec FMK.spAddLookup 'VatItemType',8,'8-صورت وضعيت پيمانكار','8.ContractStatus','8.ContractStatus','8.ContractStatus','GNR',8,''
exec FMK.spAddLookup 'VatItemType',9,'9-صورت وضعيت پيمانكار جزء','9.OwnershipStatus','9.OwnershipStatus','9.Status','GNR',9,''
exec FMK.spAddLookup 'VatItemType',10,'10-ترخيص','10.CustomsClearance','10.CustomsClearance','10.CustomsClearance','GNR',10,''
exec FMK.spAddLookup 'VatItemType',11,'11-بارنامه','11.BillOfLoading','11.BillOfLoading','11.BillOfLoading','GNR',11,''
exec FMK.spAddLookup 'VatItemType',12,'12-بيمه نامه','12.InsurancePolicy','12.InsurancePolicy','12.InsurancePolicy','GNR',12,''

exec FMK.spAddLookup 'DomesticType',1,'داخلي','Domestic',N'ناوخۆ',N'داخلي','GNR',1,''
exec FMK.spAddLookup 'DomesticType',2,'خارجي','Non Domestic',N'بياني',N'أجنبي','GNR',2,''
