exec FMK.spAddLookup 'RecordType',1,'بانك ها','Banks ',N'بانكەكان',N'البنوك','ACC',1,''
exec FMK.spAddLookup 'RecordType',2,'صندوق ها','Cashes ',N'بوخچەكان',N'الصناديق','ACC',2,''
exec FMK.spAddLookup 'RecordType',3,'كارت خوان ها','POS ',N'كارت‌ناسەكان',N'أجهزة قارئات البطاقات','ACC',3,''
exec FMK.spAddLookup 'RecordType',4,'مشتريان','Cutomers',N'كڕياران',N'الزبائن','ACC',4,''
exec FMK.spAddLookup 'RecordType',5,'تامين كنندگان','Vendors',N'دابينكاران',N'المزودكن','ACC',5,''
exec FMK.spAddLookup 'RecordType',6,'چكهاي استقرار دريافتي','Initial Receipt Cheques',N'چەكە جێگرەكاني وەرگيراو',N'الشيكات التسوية و الدفع','ACC',6,''
exec FMK.spAddLookup 'RecordType',7,'چكهاي استقرار پرداختي','Initial Payment Cheques',N'چەكە جێگرەكاني پێدان',N'الشيكات المدفوعة','ACC',7,''
exec FMK.spAddLookup 'RecordType',8,'    كالا  ','Part  ',N'كەرەستە',N'سلعة','ACC',8,''
exec FMK.spAddLookup 'RecordType',9,'    دارايي  ','Asset ',N'',N'','ACC',9,''
exec FMK.spAddLookup 'RecordType',10,'استهلاك انباشته دارايي','AssetDepreciation',N'',N'','ACC',10,''
exec FMK.spAddLookup 'RecordType',11,'واسط','Broker',N'',N'','ACC',11,''
exec FMK.spAddLookup 'RecordType',12,'تنخواه دار','Petty Cash',N'',N'','ACC',12,''

exec FMK.spAddLookup 'VoucherState',1,'موقت','Temporary',N'كاتيي',N'مؤقت','ACC',1,''
exec FMK.spAddLookup 'VoucherState',2,'دائم','Permanent',N'بەردەوام',N'الدائم','ACC',2,''

exec FMK.spAddLookup 'VoucherType',1,'عمومي','General',N'گشتيي',N'عام','ACC',1,''
exec FMK.spAddLookup 'VoucherType',2,'ساير سيستم ها','Other Systems',N'سيستەمەكاني ديكە',N'أنظمة أخرى','ACC',2,''
exec FMK.spAddLookup 'VoucherType',3,'بستن حسابها','Close Accounts',N'داخستني ژمێرەكان',N'إغلاق الحسابات','ACC',3,''
exec FMK.spAddLookup 'VoucherType',4,'اختتاميه','Closing',N'كۆتايي',N'إغلاق','ACC',4,''
exec FMK.spAddLookup 'VoucherType',5,'افتتاحيه','Opening',N'كرانەوە',N'افتتاح','ACC',5,''
exec FMK.spAddLookup 'VoucherType',6,'تسعير','Currency Conversion',N'پارە گۆڕينەوە',N'التسعكر','ACC',6,''
