---update accounts
IF Object_ID('ACC.spCorrectAccountsTolidi') IS NOT NULL
	DROP PROCEDURE ACC.spCorrectAccountsTolidi
GO
CREATE PROCEDURE ACC.spCorrectAccountsTolidi
AS

BEGIN

UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = -5
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 1
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 2
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 3
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 4
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 5
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 6
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 7 AND ParentAccountRef =-5
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 8
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 9
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 11
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 12
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 13
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 14
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 15
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 16
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 17
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 18
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 19
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 20
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 21
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 22
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 23
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 24
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 25
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 26
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 27
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 28
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 29
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 30
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 31
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 32
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 33
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 34
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 35
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 36
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 37
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 38
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 39
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 40
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 42
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 43
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 44
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 45
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 46
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 47
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 48
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 49
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 52
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 53
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 54
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 1 WHERE AccountId = 57
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 58
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 63
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 64
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 65
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 66
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 67
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 72
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 74
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 75
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 78
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 79
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 80
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 81
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 83
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 86
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 87
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 88
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 89
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 90
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 91
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 92
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 93
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 94
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 95
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 96
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 97
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 99
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 103
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 104
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 105
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 109
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 110
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 111
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 112
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 114
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 115
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 116
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 117
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 118
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 120
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 121
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 122
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 123
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 131
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 134
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 135
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 136
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 137
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 138
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 139
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 140
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 141
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 142
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 143
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 144
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 145
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 149
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 150
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 151
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 152
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 153
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 154
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 155
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 156
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 157
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 158
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 159
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 160
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 161
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 162
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 163
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 164
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 174
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 0 WHERE AccountId = 177
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 178
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 179
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 180
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 181
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 182
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 183
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 184
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 185
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 186
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 187
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 188
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 189
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 190
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 192
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 193
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 195
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 196
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 198
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 199
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 200
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 202
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 203
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 204
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 205
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 206
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 207
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 208
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 209
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 210
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 211
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 212
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 213
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 214
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 215
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 216
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 217
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 219
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 220
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 221
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 222
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 223
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 225
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 226
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 227
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 228
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 229
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 230
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 231
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 232
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 238
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 239
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 240
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 248
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 249
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 250
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 251
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 253
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 254
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 255
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 256
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 257
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 258
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 400
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 401
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 402
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 403
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 404
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 405
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 406
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 407
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 409
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 410
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 411
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 1 WHERE AccountId = 412
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 413
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 414
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 415
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 416
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 417
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 418
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 419
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 420
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 421
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 422
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 423
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 1 ,HasTracking = 0 WHERE AccountId = 424
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 425
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 426
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 0 WHERE AccountId = 427
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 428
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 1 WHERE AccountId = 429
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 0 WHERE AccountId = 430
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 431
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 432
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 433
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 434
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 435

END
 
 GO