---update accounts
IF Object_ID('ACC.spCorrectAccountsKhadamati') IS NOT NULL
	DROP PROCEDURE ACC.spCorrectAccountsKhadamati
GO
CREATE PROCEDURE ACC.spCorrectAccountsKhadamati
AS

BEGIN

UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = -5
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 1
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 2
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 3
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 4
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 5
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 6
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 8
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 9
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 11
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 13
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 14
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 16
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 17
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 18
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 22
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 23
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 24
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 31
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 33
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 35
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 36
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 38
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 39
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 41
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 42
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 43
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 45
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 48
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 49
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 51
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 52
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 53
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 55
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 56
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 57
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 58
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 59
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 60
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 63
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 70
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 71
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 72
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 1 WHERE AccountId = 75
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 76
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 79
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 83
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 84
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 89
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 91
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 99
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 131
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 132
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 133
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 135
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 138
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 141
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 145
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 146
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 150
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 154
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 155
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 185
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 186
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 187
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 188
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 189
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 190
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 193
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 195
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 198
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 199
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 200
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 201
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 203
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 209
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 213
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 217
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 218
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 219
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 231
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 232
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 234
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 248
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 249
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 253
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 254
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 255
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 258
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 260
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 261
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 263
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 264
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 265
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 266
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 269
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 275
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 276
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 284
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 285
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 286
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 288
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 290
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 291
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 293
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 294
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 298
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 299
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 301
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 302
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 309
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 310
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 311
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 313
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 314
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 315
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 329
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 346
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 347
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 348
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 349
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 350
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 353
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 354
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 357
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 400
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 401
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 402
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 403
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 404
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 405
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 409
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 410
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 411
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 1 WHERE AccountId = 412
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 413
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 414
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 415
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 416
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 417
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 418
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 419
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 420
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 421
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 425
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 428
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 431
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 432
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 433
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 434
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 435

END
 
 GO