---update accounts
IF Object_ID('ACC.spCorrectAccountsBazargani') IS NOT NULL
	DROP PROCEDURE ACC.spCorrectAccountsBazargani
GO
CREATE PROCEDURE ACC.spCorrectAccountsBazargani
AS

BEGIN
 
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = -5
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 1
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 2
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 3
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 4
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 5
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 6
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 7 AND ParentAccountRef = -5
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 8
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 9
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 10
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 11
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 12
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 13
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 14
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 16
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 17
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 18
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 19
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 20
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 21
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 22
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 23
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 24
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 25
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 26
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 27
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 28
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 29
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 30
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 31
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 32
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 33
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 34
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 35
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 36
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 37
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 38
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 39

UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 41
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 42
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 43
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 44
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 45
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 46
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 47
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 48
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 49
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 1 WHERE AccountId = 52
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 53
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 58
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 1 WHERE AccountId = 59
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 60
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 61
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 62
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 67
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 69
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 70
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 71
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 16
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 77
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 78
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 79
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 80
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 81
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 82
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 83
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 84
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 85
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 86
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 87
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 88
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 90
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 92
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 93
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 94
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 98
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 99
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 100
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 101
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 102
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 103
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 104
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 105
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 106
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 113
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 117
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 118
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 119
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 120
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 121
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 122
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 123
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 124
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 126
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 127
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 130
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 131
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 132
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 133
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 134
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 135
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 136
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 137
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 128
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 139
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 140
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 141
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 142
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 143
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 144
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 145
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 146
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 147
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 148
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 158
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 0 WHERE AccountId = 161
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 162
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 163
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 164
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 165
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 166
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 167
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 168
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 169
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 170
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 171
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 172
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 173
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 175
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 176
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 177
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 178
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 179
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 180
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 181
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 182
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 183
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 184
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 185
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 186
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 187
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 188
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 189
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 190
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 191
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 193
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 194
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 195
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 196
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 197
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 198
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 199
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 200
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 201
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 202
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 203
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 204
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 205
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 206
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 207
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 208
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 209
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 400
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 401
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 402
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 403
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 404
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 405
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 407
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 409
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 410
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 411
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 1 WHERE AccountId = 412
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 413
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 414
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 415
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 416
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 417
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 418
UPDATE Acc.Account set BalanceType = 3, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 419
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 1 ,HasTracking = 1 WHERE AccountId = 420
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 421
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 422
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 423
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 424
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 425
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 426
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 427
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 428
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 429
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 430
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 431
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 432
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 433
UPDATE Acc.Account set BalanceType = 2, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 434
UPDATE Acc.Account set BalanceType = 1, HasCurrency = 0 ,HasTracking = 0 WHERE AccountId = 435

 END
 
 GO